package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table appraisalexpertidea
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 11 16:22:42 CST 2017
 */
public class AppraisalExpertIdea extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   专家鉴定意见ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.AppraisalIdeaID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String appraisalideaid;

    /**
     * Database Column Remarks:
     *   业务数据ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.DataId
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String dataid;

    /**
     * Database Column Remarks:
     *   鉴定日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.ApprDate
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private Date apprdate;

    /**
     * Database Column Remarks:
     *   专家id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.expert_Id
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String expertId;

    /**
     * Database Column Remarks:
     *   专家鉴定意见
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.ApprExpert_Opinion
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String apprexpertOpinion;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertidea.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appraisalexpertidea
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.AppraisalIdeaID
     *
     * @return the value of appraisalexpertidea.AppraisalIdeaID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getAppraisalideaid() {
        return appraisalideaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.AppraisalIdeaID
     *
     * @param appraisalideaid the value for appraisalexpertidea.AppraisalIdeaID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setAppraisalideaid(String appraisalideaid) {
        this.appraisalideaid = appraisalideaid == null ? null : appraisalideaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.DataId
     *
     * @return the value of appraisalexpertidea.DataId
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.DataId
     *
     * @param dataid the value for appraisalexpertidea.DataId
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setDataid(String dataid) {
        this.dataid = dataid == null ? null : dataid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.ApprDate
     *
     * @return the value of appraisalexpertidea.ApprDate
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public Date getApprdate() {
        return apprdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.ApprDate
     *
     * @param apprdate the value for appraisalexpertidea.ApprDate
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setApprdate(Date apprdate) {
        this.apprdate = apprdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.expert_Id
     *
     * @return the value of appraisalexpertidea.expert_Id
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getExpertId() {
        return expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.expert_Id
     *
     * @param expertId the value for appraisalexpertidea.expert_Id
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setExpertId(String expertId) {
        this.expertId = expertId == null ? null : expertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.ApprExpert_Opinion
     *
     * @return the value of appraisalexpertidea.ApprExpert_Opinion
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getApprexpertOpinion() {
        return apprexpertOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.ApprExpert_Opinion
     *
     * @param apprexpertOpinion the value for appraisalexpertidea.ApprExpert_Opinion
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setApprexpertOpinion(String apprexpertOpinion) {
        this.apprexpertOpinion = apprexpertOpinion == null ? null : apprexpertOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.Updating_UID
     *
     * @return the value of appraisalexpertidea.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.Updating_UID
     *
     * @param updatingUid the value for appraisalexpertidea.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertidea.Updating_Date
     *
     * @return the value of appraisalexpertidea.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertidea.Updating_Date
     *
     * @param updatingDate the value for appraisalexpertidea.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertidea
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getAppraisalideaid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertidea
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appraisalideaid=").append(appraisalideaid);
        sb.append(", dataid=").append(dataid);
        sb.append(", apprdate=").append(apprdate);
        sb.append(", expertId=").append(expertId);
        sb.append(", apprexpertOpinion=").append(apprexpertOpinion);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertidea
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppraisalExpertIdea other = (AppraisalExpertIdea) that;
        return (this.getAppraisalideaid() == null ? other.getAppraisalideaid() == null : this.getAppraisalideaid().equals(other.getAppraisalideaid()))
            && (this.getDataid() == null ? other.getDataid() == null : this.getDataid().equals(other.getDataid()))
            && (this.getApprdate() == null ? other.getApprdate() == null : this.getApprdate().equals(other.getApprdate()))
            && (this.getExpertId() == null ? other.getExpertId() == null : this.getExpertId().equals(other.getExpertId()))
            && (this.getApprexpertOpinion() == null ? other.getApprexpertOpinion() == null : this.getApprexpertOpinion().equals(other.getApprexpertOpinion()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertidea
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppraisalideaid() == null) ? 0 : getAppraisalideaid().hashCode());
        result = prime * result + ((getDataid() == null) ? 0 : getDataid().hashCode());
        result = prime * result + ((getApprdate() == null) ? 0 : getApprdate().hashCode());
        result = prime * result + ((getExpertId() == null) ? 0 : getExpertId().hashCode());
        result = prime * result + ((getApprexpertOpinion() == null) ? 0 : getApprexpertOpinion().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}