package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table appraisalexpertinfo
 *
 * @mbg.generated do_not_delete_during_merge Mon Sep 11 16:22:42 CST 2017
 */
public class AppraisalExpertInfo extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   专家ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Expert_ID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String expertId;

    /**
     * Database Column Remarks:
     *   专家姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Expert_Name
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String expertName;

    /**
     * Database Column Remarks:
     *   与系统代码表 Sys_Code 的 Code 关联，提取代码类型为"Sex"的数据：1:男，2:女（Superior_Code <> 'xxx'）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Sex
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Birth_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String birthDate;

    /**
     * Database Column Remarks:
     *   仅描述单位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Subord_UnitName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String subordUnitname;

    /**
     * Database Column Remarks:
     *   仅描述部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Subord_DptName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String subordDptname;

    /**
     * Database Column Remarks:
     *   与系统代码表 Sys_Code 的 Code关联，提取代码类型为"LinkMode"的数据：1: 电话或传真，2: 信件或邮件（Superior_Code <> 'xxx'）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Email
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String email;

    /**
     * Database Column Remarks:
     *   作为“联系方式描述”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Comm_Address
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String commAddress;

    /**
     * Database Column Remarks:
     *   邮政编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Post_Code
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String postCode;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Contact_Tel
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String contactTel;

    /**
     * Database Column Remarks:
     *   与系统代码表 Sys_Code 的 Code 关联，提取代码类型为"Duty"的数据：1:玉器鉴定专家，2:金器鉴定专家，3:铜器鉴定专家，5:铁器鉴定专家，6:字画鉴定专家，7:陶瓷鉴定专家 等（Superior_Code <> 'xxx'）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Duty
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String duty;

    /**
     * Database Column Remarks:
     *   与系统代码表 Sys_Code 的 Code 关联，提取代码类型为"PostTitle"的数据：1:高级专家，2:高级研究员，3:主任专家 等（Superior_Code <> 'xxx'）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Post_Title
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String postTitle;

    /**
     * Database Column Remarks:
     *   毕业院校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Graduated_College
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String graduatedCollege;

    /**
     * Database Column Remarks:
     *   鉴定方向
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Appr_Orientation
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String apprOrientation;

    /**
     * Database Column Remarks:
     *   主要业绩
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Prim_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String primAchievement;

    /**
     * Database Column Remarks:
     *   鉴定成果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Appr_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String apprAchievement;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Remark
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalexpertinfo.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appraisalexpertinfo
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Expert_ID
     *
     * @return the value of appraisalexpertinfo.Expert_ID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getExpertId() {
        return expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Expert_ID
     *
     * @param expertId the value for appraisalexpertinfo.Expert_ID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setExpertId(String expertId) {
        this.expertId = expertId == null ? null : expertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Expert_Name
     *
     * @return the value of appraisalexpertinfo.Expert_Name
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getExpertName() {
        return expertName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Expert_Name
     *
     * @param expertName the value for appraisalexpertinfo.Expert_Name
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setExpertName(String expertName) {
        this.expertName = expertName == null ? null : expertName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Sex
     *
     * @return the value of appraisalexpertinfo.Sex
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Sex
     *
     * @param sex the value for appraisalexpertinfo.Sex
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Birth_Date
     *
     * @return the value of appraisalexpertinfo.Birth_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Birth_Date
     *
     * @param birthDate the value for appraisalexpertinfo.Birth_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate == null ? null : birthDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Subord_UnitName
     *
     * @return the value of appraisalexpertinfo.Subord_UnitName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getSubordUnitname() {
        return subordUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Subord_UnitName
     *
     * @param subordUnitname the value for appraisalexpertinfo.Subord_UnitName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setSubordUnitname(String subordUnitname) {
        this.subordUnitname = subordUnitname == null ? null : subordUnitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Subord_DptName
     *
     * @return the value of appraisalexpertinfo.Subord_DptName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getSubordDptname() {
        return subordDptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Subord_DptName
     *
     * @param subordDptname the value for appraisalexpertinfo.Subord_DptName
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setSubordDptname(String subordDptname) {
        this.subordDptname = subordDptname == null ? null : subordDptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Email
     *
     * @return the value of appraisalexpertinfo.Email
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Email
     *
     * @param email the value for appraisalexpertinfo.Email
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Comm_Address
     *
     * @return the value of appraisalexpertinfo.Comm_Address
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getCommAddress() {
        return commAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Comm_Address
     *
     * @param commAddress the value for appraisalexpertinfo.Comm_Address
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setCommAddress(String commAddress) {
        this.commAddress = commAddress == null ? null : commAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Post_Code
     *
     * @return the value of appraisalexpertinfo.Post_Code
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Post_Code
     *
     * @param postCode the value for appraisalexpertinfo.Post_Code
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Contact_Tel
     *
     * @return the value of appraisalexpertinfo.Contact_Tel
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Contact_Tel
     *
     * @param contactTel the value for appraisalexpertinfo.Contact_Tel
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Duty
     *
     * @return the value of appraisalexpertinfo.Duty
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Duty
     *
     * @param duty the value for appraisalexpertinfo.Duty
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Post_Title
     *
     * @return the value of appraisalexpertinfo.Post_Title
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Post_Title
     *
     * @param postTitle the value for appraisalexpertinfo.Post_Title
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Graduated_College
     *
     * @return the value of appraisalexpertinfo.Graduated_College
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getGraduatedCollege() {
        return graduatedCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Graduated_College
     *
     * @param graduatedCollege the value for appraisalexpertinfo.Graduated_College
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setGraduatedCollege(String graduatedCollege) {
        this.graduatedCollege = graduatedCollege == null ? null : graduatedCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Appr_Orientation
     *
     * @return the value of appraisalexpertinfo.Appr_Orientation
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getApprOrientation() {
        return apprOrientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Appr_Orientation
     *
     * @param apprOrientation the value for appraisalexpertinfo.Appr_Orientation
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setApprOrientation(String apprOrientation) {
        this.apprOrientation = apprOrientation == null ? null : apprOrientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Prim_Achievement
     *
     * @return the value of appraisalexpertinfo.Prim_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getPrimAchievement() {
        return primAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Prim_Achievement
     *
     * @param primAchievement the value for appraisalexpertinfo.Prim_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setPrimAchievement(String primAchievement) {
        this.primAchievement = primAchievement == null ? null : primAchievement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Appr_Achievement
     *
     * @return the value of appraisalexpertinfo.Appr_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getApprAchievement() {
        return apprAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Appr_Achievement
     *
     * @param apprAchievement the value for appraisalexpertinfo.Appr_Achievement
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setApprAchievement(String apprAchievement) {
        this.apprAchievement = apprAchievement == null ? null : apprAchievement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Remark
     *
     * @return the value of appraisalexpertinfo.Remark
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Remark
     *
     * @param remark the value for appraisalexpertinfo.Remark
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Updating_UID
     *
     * @return the value of appraisalexpertinfo.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Updating_UID
     *
     * @param updatingUid the value for appraisalexpertinfo.Updating_UID
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalexpertinfo.Updating_Date
     *
     * @return the value of appraisalexpertinfo.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalexpertinfo.Updating_Date
     *
     * @param updatingDate the value for appraisalexpertinfo.Updating_Date
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertinfo
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getExpertId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertinfo
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", expertId=").append(expertId);
        sb.append(", expertName=").append(expertName);
        sb.append(", sex=").append(sex);
        sb.append(", birthDate=").append(birthDate);
        sb.append(", subordUnitname=").append(subordUnitname);
        sb.append(", subordDptname=").append(subordDptname);
        sb.append(", email=").append(email);
        sb.append(", commAddress=").append(commAddress);
        sb.append(", postCode=").append(postCode);
        sb.append(", contactTel=").append(contactTel);
        sb.append(", duty=").append(duty);
        sb.append(", postTitle=").append(postTitle);
        sb.append(", graduatedCollege=").append(graduatedCollege);
        sb.append(", apprOrientation=").append(apprOrientation);
        sb.append(", primAchievement=").append(primAchievement);
        sb.append(", apprAchievement=").append(apprAchievement);
        sb.append(", remark=").append(remark);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertinfo
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppraisalExpertInfo other = (AppraisalExpertInfo) that;
        return (this.getExpertId() == null ? other.getExpertId() == null : this.getExpertId().equals(other.getExpertId()))
            && (this.getExpertName() == null ? other.getExpertName() == null : this.getExpertName().equals(other.getExpertName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getBirthDate() == null ? other.getBirthDate() == null : this.getBirthDate().equals(other.getBirthDate()))
            && (this.getSubordUnitname() == null ? other.getSubordUnitname() == null : this.getSubordUnitname().equals(other.getSubordUnitname()))
            && (this.getSubordDptname() == null ? other.getSubordDptname() == null : this.getSubordDptname().equals(other.getSubordDptname()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCommAddress() == null ? other.getCommAddress() == null : this.getCommAddress().equals(other.getCommAddress()))
            && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
            && (this.getContactTel() == null ? other.getContactTel() == null : this.getContactTel().equals(other.getContactTel()))
            && (this.getDuty() == null ? other.getDuty() == null : this.getDuty().equals(other.getDuty()))
            && (this.getPostTitle() == null ? other.getPostTitle() == null : this.getPostTitle().equals(other.getPostTitle()))
            && (this.getGraduatedCollege() == null ? other.getGraduatedCollege() == null : this.getGraduatedCollege().equals(other.getGraduatedCollege()))
            && (this.getApprOrientation() == null ? other.getApprOrientation() == null : this.getApprOrientation().equals(other.getApprOrientation()))
            && (this.getPrimAchievement() == null ? other.getPrimAchievement() == null : this.getPrimAchievement().equals(other.getPrimAchievement()))
            && (this.getApprAchievement() == null ? other.getApprAchievement() == null : this.getApprAchievement().equals(other.getApprAchievement()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalexpertinfo
     *
     * @mbg.generated Mon Sep 11 16:22:42 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getExpertId() == null) ? 0 : getExpertId().hashCode());
        result = prime * result + ((getExpertName() == null) ? 0 : getExpertName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBirthDate() == null) ? 0 : getBirthDate().hashCode());
        result = prime * result + ((getSubordUnitname() == null) ? 0 : getSubordUnitname().hashCode());
        result = prime * result + ((getSubordDptname() == null) ? 0 : getSubordDptname().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCommAddress() == null) ? 0 : getCommAddress().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getContactTel() == null) ? 0 : getContactTel().hashCode());
        result = prime * result + ((getDuty() == null) ? 0 : getDuty().hashCode());
        result = prime * result + ((getPostTitle() == null) ? 0 : getPostTitle().hashCode());
        result = prime * result + ((getGraduatedCollege() == null) ? 0 : getGraduatedCollege().hashCode());
        result = prime * result + ((getApprOrientation() == null) ? 0 : getApprOrientation().hashCode());
        result = prime * result + ((getPrimAchievement() == null) ? 0 : getPrimAchievement().hashCode());
        result = prime * result + ((getApprAchievement() == null) ? 0 : getApprAchievement().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}