package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table appraisalinfo
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class Appraisalinfo extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   鉴定任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.AppraisalID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String appraisalid;

    /**
     * Database Column Remarks:
     *   逻辑主键1，由系统生成，
            规则： 鉴定业务+yyyymm_nnnn
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_Batch_No
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprBatchNo;

    /**
     * Database Column Remarks:
     *   逻辑主键2，从对应于本表文物ID的文物基础表一、二、三中的文物中提取文物信息（鉴定业务类型为“1:征集鉴定”时，这些文物信息的文物ID与征集信息登记表中的文物ID对应）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String culid;

    /**
     * Database Column Remarks:
     *   鉴定后文物名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_A0102
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprA0102;

    /**
     * Database Column Remarks:
     *   鉴定后藏品级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_B0401
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprB0401;

    /**
     * Database Column Remarks:
     *   鉴定后藏品质地
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_A0610
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprA0610;

    /**
     * Database Column Remarks:
     *   鉴定后藏品年代
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_A0310
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprA0310;

    /**
     * Database Column Remarks:
     *   鉴定后藏品估价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_B0256
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private BigDecimal apprB0256;

    /**
     * Database Column Remarks:
     *   1:征集鉴定、2: 保管鉴定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprType;

    /**
     * Database Column Remarks:
     *   申请人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Proposer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String proposer;

    /**
     * Database Column Remarks:
     *   申请时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.ApplicationDate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date applicationdate;

    /**
     * Database Column Remarks:
     *   鉴定原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.ApplicationReasons
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String applicationreasons;

    /**
     * Database Column Remarks:
     *   申请备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.ApplicationRemark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String applicationremark;

    /**
     * Database Column Remarks:
     *   鉴定开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Start_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     *   鉴定时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.End_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   鉴定地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_Locate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprLocate;

    /**
     * Database Column Remarks:
     *   鉴定负责人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String compere;

    /**
     * Database Column Remarks:
     *   参与鉴定专家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appraiser
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String appraiser;

    /**
     * Database Column Remarks:
     *   鉴定意见
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_Opinion
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprOpinion;

    /**
     * Database Column Remarks:
     *   鉴定备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Appr_Remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String apprRemark;

    /**
     * Database Column Remarks:
     *   0、未鉴定，1、已鉴定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String status;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingDate;

    /**
     * Database Column Remarks:
     *   证书编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appraisalinfo.CertificateNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String certificateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appraisalinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.AppraisalID
     *
     * @return the value of appraisalinfo.AppraisalID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAppraisalid() {
        return appraisalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.AppraisalID
     *
     * @param appraisalid the value for appraisalinfo.AppraisalID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAppraisalid(String appraisalid) {
        this.appraisalid = appraisalid == null ? null : appraisalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_Batch_No
     *
     * @return the value of appraisalinfo.Appr_Batch_No
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprBatchNo() {
        return apprBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_Batch_No
     *
     * @param apprBatchNo the value for appraisalinfo.Appr_Batch_No
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprBatchNo(String apprBatchNo) {
        this.apprBatchNo = apprBatchNo == null ? null : apprBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.CulID
     *
     * @return the value of appraisalinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCulid() {
        return culid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.CulID
     *
     * @param culid the value for appraisalinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCulid(String culid) {
        this.culid = culid == null ? null : culid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_A0102
     *
     * @return the value of appraisalinfo.Appr_A0102
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprA0102() {
        return apprA0102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_A0102
     *
     * @param apprA0102 the value for appraisalinfo.Appr_A0102
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprA0102(String apprA0102) {
        this.apprA0102 = apprA0102 == null ? null : apprA0102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_B0401
     *
     * @return the value of appraisalinfo.Appr_B0401
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprB0401() {
        return apprB0401;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_B0401
     *
     * @param apprB0401 the value for appraisalinfo.Appr_B0401
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprB0401(String apprB0401) {
        this.apprB0401 = apprB0401 == null ? null : apprB0401.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_A0610
     *
     * @return the value of appraisalinfo.Appr_A0610
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprA0610() {
        return apprA0610;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_A0610
     *
     * @param apprA0610 the value for appraisalinfo.Appr_A0610
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprA0610(String apprA0610) {
        this.apprA0610 = apprA0610 == null ? null : apprA0610.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_A0310
     *
     * @return the value of appraisalinfo.Appr_A0310
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprA0310() {
        return apprA0310;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_A0310
     *
     * @param apprA0310 the value for appraisalinfo.Appr_A0310
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprA0310(String apprA0310) {
        this.apprA0310 = apprA0310 == null ? null : apprA0310.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_B0256
     *
     * @return the value of appraisalinfo.Appr_B0256
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public BigDecimal getApprB0256() {
        return apprB0256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_B0256
     *
     * @param apprB0256 the value for appraisalinfo.Appr_B0256
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprB0256(BigDecimal apprB0256) {
        this.apprB0256 = apprB0256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_Type
     *
     * @return the value of appraisalinfo.Appr_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprType() {
        return apprType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_Type
     *
     * @param apprType the value for appraisalinfo.Appr_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprType(String apprType) {
        this.apprType = apprType == null ? null : apprType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Proposer
     *
     * @return the value of appraisalinfo.Proposer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getProposer() {
        return proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Proposer
     *
     * @param proposer the value for appraisalinfo.Proposer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setProposer(String proposer) {
        this.proposer = proposer == null ? null : proposer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.ApplicationDate
     *
     * @return the value of appraisalinfo.ApplicationDate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getApplicationdate() {
        return applicationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.ApplicationDate
     *
     * @param applicationdate the value for appraisalinfo.ApplicationDate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApplicationdate(Date applicationdate) {
        this.applicationdate = applicationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.ApplicationReasons
     *
     * @return the value of appraisalinfo.ApplicationReasons
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApplicationreasons() {
        return applicationreasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.ApplicationReasons
     *
     * @param applicationreasons the value for appraisalinfo.ApplicationReasons
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApplicationreasons(String applicationreasons) {
        this.applicationreasons = applicationreasons == null ? null : applicationreasons.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.ApplicationRemark
     *
     * @return the value of appraisalinfo.ApplicationRemark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApplicationremark() {
        return applicationremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.ApplicationRemark
     *
     * @param applicationremark the value for appraisalinfo.ApplicationRemark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApplicationremark(String applicationremark) {
        this.applicationremark = applicationremark == null ? null : applicationremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Start_Date
     *
     * @return the value of appraisalinfo.Start_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Start_Date
     *
     * @param startDate the value for appraisalinfo.Start_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.End_Date
     *
     * @return the value of appraisalinfo.End_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.End_Date
     *
     * @param endDate the value for appraisalinfo.End_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_Locate
     *
     * @return the value of appraisalinfo.Appr_Locate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprLocate() {
        return apprLocate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_Locate
     *
     * @param apprLocate the value for appraisalinfo.Appr_Locate
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprLocate(String apprLocate) {
        this.apprLocate = apprLocate == null ? null : apprLocate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Compere
     *
     * @return the value of appraisalinfo.Compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCompere() {
        return compere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Compere
     *
     * @param compere the value for appraisalinfo.Compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCompere(String compere) {
        this.compere = compere == null ? null : compere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appraiser
     *
     * @return the value of appraisalinfo.Appraiser
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAppraiser() {
        return appraiser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appraiser
     *
     * @param appraiser the value for appraisalinfo.Appraiser
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAppraiser(String appraiser) {
        this.appraiser = appraiser == null ? null : appraiser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_Opinion
     *
     * @return the value of appraisalinfo.Appr_Opinion
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprOpinion() {
        return apprOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_Opinion
     *
     * @param apprOpinion the value for appraisalinfo.Appr_Opinion
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprOpinion(String apprOpinion) {
        this.apprOpinion = apprOpinion == null ? null : apprOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Appr_Remark
     *
     * @return the value of appraisalinfo.Appr_Remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getApprRemark() {
        return apprRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Appr_Remark
     *
     * @param apprRemark the value for appraisalinfo.Appr_Remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setApprRemark(String apprRemark) {
        this.apprRemark = apprRemark == null ? null : apprRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Status
     *
     * @return the value of appraisalinfo.Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Status
     *
     * @param status the value for appraisalinfo.Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Updating_UID
     *
     * @return the value of appraisalinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Updating_UID
     *
     * @param updatingUid the value for appraisalinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.Updating_Date
     *
     * @return the value of appraisalinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.Updating_Date
     *
     * @param updatingDate the value for appraisalinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appraisalinfo.CertificateNo
     *
     * @return the value of appraisalinfo.CertificateNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCertificateno() {
        return certificateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appraisalinfo.CertificateNo
     *
     * @param certificateno the value for appraisalinfo.CertificateNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno == null ? null : certificateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getAppraisalid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appraisalid=").append(appraisalid);
        sb.append(", apprBatchNo=").append(apprBatchNo);
        sb.append(", culid=").append(culid);
        sb.append(", apprA0102=").append(apprA0102);
        sb.append(", apprB0401=").append(apprB0401);
        sb.append(", apprA0610=").append(apprA0610);
        sb.append(", apprA0310=").append(apprA0310);
        sb.append(", apprB0256=").append(apprB0256);
        sb.append(", apprType=").append(apprType);
        sb.append(", proposer=").append(proposer);
        sb.append(", applicationdate=").append(applicationdate);
        sb.append(", applicationreasons=").append(applicationreasons);
        sb.append(", applicationremark=").append(applicationremark);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", apprLocate=").append(apprLocate);
        sb.append(", compere=").append(compere);
        sb.append(", appraiser=").append(appraiser);
        sb.append(", apprOpinion=").append(apprOpinion);
        sb.append(", apprRemark=").append(apprRemark);
        sb.append(", status=").append(status);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", certificateno=").append(certificateno);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Appraisalinfo other = (Appraisalinfo) that;
        return (this.getAppraisalid() == null ? other.getAppraisalid() == null : this.getAppraisalid().equals(other.getAppraisalid()))
            && (this.getApprBatchNo() == null ? other.getApprBatchNo() == null : this.getApprBatchNo().equals(other.getApprBatchNo()))
            && (this.getCulid() == null ? other.getCulid() == null : this.getCulid().equals(other.getCulid()))
            && (this.getApprA0102() == null ? other.getApprA0102() == null : this.getApprA0102().equals(other.getApprA0102()))
            && (this.getApprB0401() == null ? other.getApprB0401() == null : this.getApprB0401().equals(other.getApprB0401()))
            && (this.getApprA0610() == null ? other.getApprA0610() == null : this.getApprA0610().equals(other.getApprA0610()))
            && (this.getApprA0310() == null ? other.getApprA0310() == null : this.getApprA0310().equals(other.getApprA0310()))
            && (this.getApprB0256() == null ? other.getApprB0256() == null : this.getApprB0256().equals(other.getApprB0256()))
            && (this.getApprType() == null ? other.getApprType() == null : this.getApprType().equals(other.getApprType()))
            && (this.getProposer() == null ? other.getProposer() == null : this.getProposer().equals(other.getProposer()))
            && (this.getApplicationdate() == null ? other.getApplicationdate() == null : this.getApplicationdate().equals(other.getApplicationdate()))
            && (this.getApplicationreasons() == null ? other.getApplicationreasons() == null : this.getApplicationreasons().equals(other.getApplicationreasons()))
            && (this.getApplicationremark() == null ? other.getApplicationremark() == null : this.getApplicationremark().equals(other.getApplicationremark()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getApprLocate() == null ? other.getApprLocate() == null : this.getApprLocate().equals(other.getApprLocate()))
            && (this.getCompere() == null ? other.getCompere() == null : this.getCompere().equals(other.getCompere()))
            && (this.getAppraiser() == null ? other.getAppraiser() == null : this.getAppraiser().equals(other.getAppraiser()))
            && (this.getApprOpinion() == null ? other.getApprOpinion() == null : this.getApprOpinion().equals(other.getApprOpinion()))
            && (this.getApprRemark() == null ? other.getApprRemark() == null : this.getApprRemark().equals(other.getApprRemark()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()))
            && (this.getCertificateno() == null ? other.getCertificateno() == null : this.getCertificateno().equals(other.getCertificateno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appraisalinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppraisalid() == null) ? 0 : getAppraisalid().hashCode());
        result = prime * result + ((getApprBatchNo() == null) ? 0 : getApprBatchNo().hashCode());
        result = prime * result + ((getCulid() == null) ? 0 : getCulid().hashCode());
        result = prime * result + ((getApprA0102() == null) ? 0 : getApprA0102().hashCode());
        result = prime * result + ((getApprB0401() == null) ? 0 : getApprB0401().hashCode());
        result = prime * result + ((getApprA0610() == null) ? 0 : getApprA0610().hashCode());
        result = prime * result + ((getApprA0310() == null) ? 0 : getApprA0310().hashCode());
        result = prime * result + ((getApprB0256() == null) ? 0 : getApprB0256().hashCode());
        result = prime * result + ((getApprType() == null) ? 0 : getApprType().hashCode());
        result = prime * result + ((getProposer() == null) ? 0 : getProposer().hashCode());
        result = prime * result + ((getApplicationdate() == null) ? 0 : getApplicationdate().hashCode());
        result = prime * result + ((getApplicationreasons() == null) ? 0 : getApplicationreasons().hashCode());
        result = prime * result + ((getApplicationremark() == null) ? 0 : getApplicationremark().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getApprLocate() == null) ? 0 : getApprLocate().hashCode());
        result = prime * result + ((getCompere() == null) ? 0 : getCompere().hashCode());
        result = prime * result + ((getAppraiser() == null) ? 0 : getAppraiser().hashCode());
        result = prime * result + ((getApprOpinion() == null) ? 0 : getApprOpinion().hashCode());
        result = prime * result + ((getApprRemark() == null) ? 0 : getApprRemark().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        result = prime * result + ((getCertificateno() == null) ? 0 : getCertificateno().hashCode());
        return result;
    }
}