package com.museum.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.framework.model.BaseModel;

public class CollInfo extends BaseModel implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.collinfoID
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String collinfoid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.batch
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String batch;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.CollNo
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String collno;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.colldate
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private Date colldate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.price
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private BigDecimal price;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.CURRENCY
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String currency;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.collName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String collname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.culName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.culMaterial
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culmaterial;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.CulRootIn
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culrootin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.CulCondition
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culcondition;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.collPath
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String collpath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.cul_spread_path
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culSpreadPath;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.collNum
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private Integer collnum;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.culid
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String culid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.collectedman
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String collectedman;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.status
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.isAppraisal
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String isappraisal;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.isDeliver
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String isdeliver;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.unit
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String unit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column coll_info.remark
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table coll_info
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.collinfoID
	 *
	 * @return the value of coll_info.collinfoID
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCollinfoid() {
		return collinfoid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.collinfoID
	 *
	 * @param collinfoid
	 *            the value for coll_info.collinfoID
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollinfoid(String collinfoid) {
		this.collinfoid = collinfoid == null ? null : collinfoid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.batch
	 *
	 * @return the value of coll_info.batch
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getBatch() {
		return batch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.batch
	 *
	 * @param batch
	 *            the value for coll_info.batch
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setBatch(String batch) {
		this.batch = batch == null ? null : batch.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.CollNo
	 *
	 * @return the value of coll_info.CollNo
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCollno() {
		return collno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.CollNo
	 *
	 * @param collno
	 *            the value for coll_info.CollNo
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollno(String collno) {
		this.collno = collno == null ? null : collno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.colldate
	 *
	 * @return the value of coll_info.colldate
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public Date getColldate() {
		return colldate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.colldate
	 *
	 * @param colldate
	 *            the value for coll_info.colldate
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setColldate(Date colldate) {
		this.colldate = colldate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.price
	 *
	 * @return the value of coll_info.price
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.price
	 *
	 * @param price
	 *            the value for coll_info.price
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.CURRENCY
	 *
	 * @return the value of coll_info.CURRENCY
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.CURRENCY
	 *
	 * @param currency
	 *            the value for coll_info.CURRENCY
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCurrency(String currency) {
		this.currency = currency == null ? null : currency.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.collName
	 *
	 * @return the value of coll_info.collName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCollname() {
		return collname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.collName
	 *
	 * @param collname
	 *            the value for coll_info.collName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollname(String collname) {
		this.collname = collname == null ? null : collname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.culName
	 *
	 * @return the value of coll_info.culName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulname() {
		return culname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.culName
	 *
	 * @param culname
	 *            the value for coll_info.culName
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulname(String culname) {
		this.culname = culname == null ? null : culname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.culMaterial
	 *
	 * @return the value of coll_info.culMaterial
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulmaterial() {
		return culmaterial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.culMaterial
	 *
	 * @param culmaterial
	 *            the value for coll_info.culMaterial
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulmaterial(String culmaterial) {
		this.culmaterial = culmaterial == null ? null : culmaterial.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.CulRootIn
	 *
	 * @return the value of coll_info.CulRootIn
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulrootin() {
		return culrootin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.CulRootIn
	 *
	 * @param culrootin
	 *            the value for coll_info.CulRootIn
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulrootin(String culrootin) {
		this.culrootin = culrootin == null ? null : culrootin.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.CulCondition
	 *
	 * @return the value of coll_info.CulCondition
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulcondition() {
		return culcondition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.CulCondition
	 *
	 * @param culcondition
	 *            the value for coll_info.CulCondition
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulcondition(String culcondition) {
		this.culcondition = culcondition == null ? null : culcondition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.collPath
	 *
	 * @return the value of coll_info.collPath
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCollpath() {
		return collpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.collPath
	 *
	 * @param collpath
	 *            the value for coll_info.collPath
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollpath(String collpath) {
		this.collpath = collpath == null ? null : collpath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.cul_spread_path
	 *
	 * @return the value of coll_info.cul_spread_path
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulSpreadPath() {
		return culSpreadPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.cul_spread_path
	 *
	 * @param culSpreadPath
	 *            the value for coll_info.cul_spread_path
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulSpreadPath(String culSpreadPath) {
		this.culSpreadPath = culSpreadPath == null ? null : culSpreadPath
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.collNum
	 *
	 * @return the value of coll_info.collNum
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public Integer getCollnum() {
		return collnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.collNum
	 *
	 * @param collnum
	 *            the value for coll_info.collNum
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollnum(Integer collnum) {
		this.collnum = collnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.culid
	 *
	 * @return the value of coll_info.culid
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCulid() {
		return culid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.culid
	 *
	 * @param culid
	 *            the value for coll_info.culid
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCulid(String culid) {
		this.culid = culid == null ? null : culid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.collectedman
	 *
	 * @return the value of coll_info.collectedman
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getCollectedman() {
		return collectedman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.collectedman
	 *
	 * @param collectedman
	 *            the value for coll_info.collectedman
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setCollectedman(String collectedman) {
		this.collectedman = collectedman == null ? null : collectedman.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.status
	 *
	 * @return the value of coll_info.status
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.status
	 *
	 * @param status
	 *            the value for coll_info.status
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.isAppraisal
	 *
	 * @return the value of coll_info.isAppraisal
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getIsappraisal() {
		return isappraisal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.isAppraisal
	 *
	 * @param isappraisal
	 *            the value for coll_info.isAppraisal
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setIsappraisal(String isappraisal) {
		this.isappraisal = isappraisal == null ? null : isappraisal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.isDeliver
	 *
	 * @return the value of coll_info.isDeliver
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getIsdeliver() {
		return isdeliver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.isDeliver
	 *
	 * @param isdeliver
	 *            the value for coll_info.isDeliver
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setIsdeliver(String isdeliver) {
		this.isdeliver = isdeliver == null ? null : isdeliver.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.unit
	 *
	 * @return the value of coll_info.unit
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.unit
	 *
	 * @param unit
	 *            the value for coll_info.unit
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column coll_info.remark
	 *
	 * @return the value of coll_info.remark
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column coll_info.remark
	 *
	 * @param remark
	 *            the value for coll_info.remark
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coll_info
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	@Override
	public Object getPrimaryKey() {
		return this.getCollinfoid();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coll_info
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", collinfoid=").append(collinfoid);
		sb.append(", batch=").append(batch);
		sb.append(", collno=").append(collno);
		sb.append(", colldate=").append(colldate);
		sb.append(", price=").append(price);
		sb.append(", currency=").append(currency);
		sb.append(", collname=").append(collname);
		sb.append(", culname=").append(culname);
		sb.append(", culmaterial=").append(culmaterial);
		sb.append(", culrootin=").append(culrootin);
		sb.append(", culcondition=").append(culcondition);
		sb.append(", collpath=").append(collpath);
		sb.append(", culSpreadPath=").append(culSpreadPath);
		sb.append(", collnum=").append(collnum);
		sb.append(", culid=").append(culid);
		sb.append(", collectedman=").append(collectedman);
		sb.append(", status=").append(status);
		sb.append(", isappraisal=").append(isappraisal);
		sb.append(", isdeliver=").append(isdeliver);
		sb.append(", unit=").append(unit);
		sb.append(", remark=").append(remark);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coll_info
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CollInfo other = (CollInfo) that;
		return (this.getCollinfoid() == null ? other.getCollinfoid() == null
				: this.getCollinfoid().equals(other.getCollinfoid()))
				&& (this.getBatch() == null ? other.getBatch() == null : this
						.getBatch().equals(other.getBatch()))
				&& (this.getCollno() == null ? other.getCollno() == null : this
						.getCollno().equals(other.getCollno()))
				&& (this.getColldate() == null ? other.getColldate() == null
						: this.getColldate().equals(other.getColldate()))
				&& (this.getPrice() == null ? other.getPrice() == null : this
						.getPrice().equals(other.getPrice()))
				&& (this.getCurrency() == null ? other.getCurrency() == null
						: this.getCurrency().equals(other.getCurrency()))
				&& (this.getCollname() == null ? other.getCollname() == null
						: this.getCollname().equals(other.getCollname()))
				&& (this.getCulname() == null ? other.getCulname() == null
						: this.getCulname().equals(other.getCulname()))
				&& (this.getCulmaterial() == null ? other.getCulmaterial() == null
						: this.getCulmaterial().equals(other.getCulmaterial()))
				&& (this.getCulrootin() == null ? other.getCulrootin() == null
						: this.getCulrootin().equals(other.getCulrootin()))
				&& (this.getCulcondition() == null ? other.getCulcondition() == null
						: this.getCulcondition()
								.equals(other.getCulcondition()))
				&& (this.getCollpath() == null ? other.getCollpath() == null
						: this.getCollpath().equals(other.getCollpath()))
				&& (this.getCulSpreadPath() == null ? other.getCulSpreadPath() == null
						: this.getCulSpreadPath().equals(
								other.getCulSpreadPath()))
				&& (this.getCollnum() == null ? other.getCollnum() == null
						: this.getCollnum().equals(other.getCollnum()))
				&& (this.getCulid() == null ? other.getCulid() == null : this
						.getCulid().equals(other.getCulid()))
				&& (this.getCollectedman() == null ? other.getCollectedman() == null
						: this.getCollectedman()
								.equals(other.getCollectedman()))
				&& (this.getStatus() == null ? other.getStatus() == null : this
						.getStatus().equals(other.getStatus()))
				&& (this.getIsappraisal() == null ? other.getIsappraisal() == null
						: this.getIsappraisal().equals(other.getIsappraisal()))
				&& (this.getIsdeliver() == null ? other.getIsdeliver() == null
						: this.getIsdeliver().equals(other.getIsdeliver()))
				&& (this.getUnit() == null ? other.getUnit() == null : this
						.getUnit().equals(other.getUnit()))
				&& (this.getRemark() == null ? other.getRemark() == null : this
						.getRemark().equals(other.getRemark()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table coll_info
	 *
	 * @mbg.generated Sat May 06 18:00:51 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getCollinfoid() == null) ? 0 : getCollinfoid().hashCode());
		result = prime * result
				+ ((getBatch() == null) ? 0 : getBatch().hashCode());
		result = prime * result
				+ ((getCollno() == null) ? 0 : getCollno().hashCode());
		result = prime * result
				+ ((getColldate() == null) ? 0 : getColldate().hashCode());
		result = prime * result
				+ ((getPrice() == null) ? 0 : getPrice().hashCode());
		result = prime * result
				+ ((getCurrency() == null) ? 0 : getCurrency().hashCode());
		result = prime * result
				+ ((getCollname() == null) ? 0 : getCollname().hashCode());
		result = prime * result
				+ ((getCulname() == null) ? 0 : getCulname().hashCode());
		result = prime
				* result
				+ ((getCulmaterial() == null) ? 0 : getCulmaterial().hashCode());
		result = prime * result
				+ ((getCulrootin() == null) ? 0 : getCulrootin().hashCode());
		result = prime
				* result
				+ ((getCulcondition() == null) ? 0 : getCulcondition()
						.hashCode());
		result = prime * result
				+ ((getCollpath() == null) ? 0 : getCollpath().hashCode());
		result = prime
				* result
				+ ((getCulSpreadPath() == null) ? 0 : getCulSpreadPath()
						.hashCode());
		result = prime * result
				+ ((getCollnum() == null) ? 0 : getCollnum().hashCode());
		result = prime * result
				+ ((getCulid() == null) ? 0 : getCulid().hashCode());
		result = prime
				* result
				+ ((getCollectedman() == null) ? 0 : getCollectedman()
						.hashCode());
		result = prime * result
				+ ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime
				* result
				+ ((getIsappraisal() == null) ? 0 : getIsappraisal().hashCode());
		result = prime * result
				+ ((getIsdeliver() == null) ? 0 : getIsdeliver().hashCode());
		result = prime * result
				+ ((getUnit() == null) ? 0 : getUnit().hashCode());
		result = prime * result
				+ ((getRemark() == null) ? 0 : getRemark().hashCode());
		return result;
	}
}