package com.museum.model;

import java.io.Serializable;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table culturalreliccopy
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class CulturalreliccopyWithBLOBs extends Culturalreliccopy implements Serializable {
    /**
     * Database Column Remarks:
     *   复制方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.COPY_MOTHOD
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private byte[] copyMothod;

    /**
     * Database Column Remarks:
     *   复制过程
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Copy_Process
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private byte[] copyProcess;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private byte[] remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.COPY_MOTHOD
     *
     * @return the value of culturalreliccopy.COPY_MOTHOD
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public byte[] getCopyMothod() {
        return copyMothod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.COPY_MOTHOD
     *
     * @param copyMothod the value for culturalreliccopy.COPY_MOTHOD
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyMothod(byte[] copyMothod) {
        this.copyMothod = copyMothod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Copy_Process
     *
     * @return the value of culturalreliccopy.Copy_Process
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public byte[] getCopyProcess() {
        return copyProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Copy_Process
     *
     * @param copyProcess the value for culturalreliccopy.Copy_Process
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyProcess(byte[] copyProcess) {
        this.copyProcess = copyProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.remark
     *
     * @return the value of culturalreliccopy.remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public byte[] getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.remark
     *
     * @param remark the value for culturalreliccopy.remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRemark(byte[] remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", copyMothod=").append(copyMothod);
        sb.append(", copyProcess=").append(copyProcess);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CulturalreliccopyWithBLOBs other = (CulturalreliccopyWithBLOBs) that;
        return (this.getCulturalreliccopyid() == null ? other.getCulturalreliccopyid() == null : this.getCulturalreliccopyid().equals(other.getCulturalreliccopyid()))
            && (this.getOutvoucherId() == null ? other.getOutvoucherId() == null : this.getOutvoucherId().equals(other.getOutvoucherId()))
            && (this.getCopyType() == null ? other.getCopyType() == null : this.getCopyType().equals(other.getCopyType()))
            && (this.getCulid() == null ? other.getCulid() == null : this.getCulid().equals(other.getCulid()))
            && (this.getCopyDate() == null ? other.getCopyDate() == null : this.getCopyDate().equals(other.getCopyDate()))
            && (this.getCopyMan() == null ? other.getCopyMan() == null : this.getCopyMan().equals(other.getCopyMan()))
            && (this.getCopyPurpose() == null ? other.getCopyPurpose() == null : this.getCopyPurpose().equals(other.getCopyPurpose()))
            && (this.getEstimateCopyQty() == null ? other.getEstimateCopyQty() == null : this.getEstimateCopyQty().equals(other.getEstimateCopyQty()))
            && (this.getActualCopyQty() == null ? other.getActualCopyQty() == null : this.getActualCopyQty().equals(other.getActualCopyQty()))
            && (this.getCopyStatus() == null ? other.getCopyStatus() == null : this.getCopyStatus().equals(other.getCopyStatus()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()))
            && (Arrays.equals(this.getCopyMothod(), other.getCopyMothod()))
            && (Arrays.equals(this.getCopyProcess(), other.getCopyProcess()))
            && (Arrays.equals(this.getRemark(), other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCulturalreliccopyid() == null) ? 0 : getCulturalreliccopyid().hashCode());
        result = prime * result + ((getOutvoucherId() == null) ? 0 : getOutvoucherId().hashCode());
        result = prime * result + ((getCopyType() == null) ? 0 : getCopyType().hashCode());
        result = prime * result + ((getCulid() == null) ? 0 : getCulid().hashCode());
        result = prime * result + ((getCopyDate() == null) ? 0 : getCopyDate().hashCode());
        result = prime * result + ((getCopyMan() == null) ? 0 : getCopyMan().hashCode());
        result = prime * result + ((getCopyPurpose() == null) ? 0 : getCopyPurpose().hashCode());
        result = prime * result + ((getEstimateCopyQty() == null) ? 0 : getEstimateCopyQty().hashCode());
        result = prime * result + ((getActualCopyQty() == null) ? 0 : getActualCopyQty().hashCode());
        result = prime * result + ((getCopyStatus() == null) ? 0 : getCopyStatus().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        result = prime * result + (Arrays.hashCode(getCopyMothod()));
        result = prime * result + (Arrays.hashCode(getCopyProcess()));
        result = prime * result + (Arrays.hashCode(getRemark()));
        return result;
    }
}