package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table culturalreliccopy
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class Culturalreliccopy extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   复制登记任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.CulturalRelicCopyID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String culturalreliccopyid;

    /**
     * Database Column Remarks:
     *   作为逻辑外键，与出库凭证表 Cul_OVMain 的 OutVoucher_ID 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.OUTVOUCHER_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String outvoucherId;

    /**
     * Database Column Remarks:
     *   1: 馆内文物复制，2: 馆外文物复制
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Copy_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String copyType;

    /**
     * Database Column Remarks:
     *   从文物基础表 Cul_MainCul1/2/3（文物一、二、三）中提取文物信息（对于“复制业务类型”为“2:馆外文物复制”的复制原件文物而言，文物基础表中的“管理类型”为“外来复制原件”）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String culid;

    /**
     * Database Column Remarks:
     *   复制日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.COPY_DATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date copyDate;

    /**
     * Database Column Remarks:
     *   复制人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.COPY_MAN
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String copyMan;

    /**
     * Database Column Remarks:
     *   复制目的
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Copy_Purpose
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String copyPurpose;

    /**
     * Database Column Remarks:
     *   仅接收数字0至9的组合，单位为"件"。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Estimate_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String estimateCopyQty;

    /**
     * Database Column Remarks:
     *   仅接收数字0至9的组合，单位为"件"。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Actual_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String actualCopyQty;

    /**
     * Database Column Remarks:
     *   1:未确认，2:已确认
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Copy_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String copyStatus;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column culturalreliccopy.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.CulturalRelicCopyID
     *
     * @return the value of culturalreliccopy.CulturalRelicCopyID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCulturalreliccopyid() {
        return culturalreliccopyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.CulturalRelicCopyID
     *
     * @param culturalreliccopyid the value for culturalreliccopy.CulturalRelicCopyID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCulturalreliccopyid(String culturalreliccopyid) {
        this.culturalreliccopyid = culturalreliccopyid == null ? null : culturalreliccopyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.OUTVOUCHER_ID
     *
     * @return the value of culturalreliccopy.OUTVOUCHER_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getOutvoucherId() {
        return outvoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.OUTVOUCHER_ID
     *
     * @param outvoucherId the value for culturalreliccopy.OUTVOUCHER_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setOutvoucherId(String outvoucherId) {
        this.outvoucherId = outvoucherId == null ? null : outvoucherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Copy_Type
     *
     * @return the value of culturalreliccopy.Copy_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCopyType() {
        return copyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Copy_Type
     *
     * @param copyType the value for culturalreliccopy.Copy_Type
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyType(String copyType) {
        this.copyType = copyType == null ? null : copyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.CulID
     *
     * @return the value of culturalreliccopy.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCulid() {
        return culid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.CulID
     *
     * @param culid the value for culturalreliccopy.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCulid(String culid) {
        this.culid = culid == null ? null : culid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.COPY_DATE
     *
     * @return the value of culturalreliccopy.COPY_DATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getCopyDate() {
        return copyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.COPY_DATE
     *
     * @param copyDate the value for culturalreliccopy.COPY_DATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyDate(Date copyDate) {
        this.copyDate = copyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.COPY_MAN
     *
     * @return the value of culturalreliccopy.COPY_MAN
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCopyMan() {
        return copyMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.COPY_MAN
     *
     * @param copyMan the value for culturalreliccopy.COPY_MAN
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyMan(String copyMan) {
        this.copyMan = copyMan == null ? null : copyMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Copy_Purpose
     *
     * @return the value of culturalreliccopy.Copy_Purpose
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCopyPurpose() {
        return copyPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Copy_Purpose
     *
     * @param copyPurpose the value for culturalreliccopy.Copy_Purpose
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyPurpose(String copyPurpose) {
        this.copyPurpose = copyPurpose == null ? null : copyPurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Estimate_Copy_Qty
     *
     * @return the value of culturalreliccopy.Estimate_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getEstimateCopyQty() {
        return estimateCopyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Estimate_Copy_Qty
     *
     * @param estimateCopyQty the value for culturalreliccopy.Estimate_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setEstimateCopyQty(String estimateCopyQty) {
        this.estimateCopyQty = estimateCopyQty == null ? null : estimateCopyQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Actual_Copy_Qty
     *
     * @return the value of culturalreliccopy.Actual_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getActualCopyQty() {
        return actualCopyQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Actual_Copy_Qty
     *
     * @param actualCopyQty the value for culturalreliccopy.Actual_Copy_Qty
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setActualCopyQty(String actualCopyQty) {
        this.actualCopyQty = actualCopyQty == null ? null : actualCopyQty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Copy_Status
     *
     * @return the value of culturalreliccopy.Copy_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCopyStatus() {
        return copyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Copy_Status
     *
     * @param copyStatus the value for culturalreliccopy.Copy_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCopyStatus(String copyStatus) {
        this.copyStatus = copyStatus == null ? null : copyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Updating_UID
     *
     * @return the value of culturalreliccopy.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Updating_UID
     *
     * @param updatingUid the value for culturalreliccopy.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column culturalreliccopy.Updating_Date
     *
     * @return the value of culturalreliccopy.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column culturalreliccopy.Updating_Date
     *
     * @param updatingDate the value for culturalreliccopy.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getCulturalreliccopyid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", culturalreliccopyid=").append(culturalreliccopyid);
        sb.append(", outvoucherId=").append(outvoucherId);
        sb.append(", copyType=").append(copyType);
        sb.append(", culid=").append(culid);
        sb.append(", copyDate=").append(copyDate);
        sb.append(", copyMan=").append(copyMan);
        sb.append(", copyPurpose=").append(copyPurpose);
        sb.append(", estimateCopyQty=").append(estimateCopyQty);
        sb.append(", actualCopyQty=").append(actualCopyQty);
        sb.append(", copyStatus=").append(copyStatus);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Culturalreliccopy other = (Culturalreliccopy) that;
        return (this.getCulturalreliccopyid() == null ? other.getCulturalreliccopyid() == null : this.getCulturalreliccopyid().equals(other.getCulturalreliccopyid()))
            && (this.getOutvoucherId() == null ? other.getOutvoucherId() == null : this.getOutvoucherId().equals(other.getOutvoucherId()))
            && (this.getCopyType() == null ? other.getCopyType() == null : this.getCopyType().equals(other.getCopyType()))
            && (this.getCulid() == null ? other.getCulid() == null : this.getCulid().equals(other.getCulid()))
            && (this.getCopyDate() == null ? other.getCopyDate() == null : this.getCopyDate().equals(other.getCopyDate()))
            && (this.getCopyMan() == null ? other.getCopyMan() == null : this.getCopyMan().equals(other.getCopyMan()))
            && (this.getCopyPurpose() == null ? other.getCopyPurpose() == null : this.getCopyPurpose().equals(other.getCopyPurpose()))
            && (this.getEstimateCopyQty() == null ? other.getEstimateCopyQty() == null : this.getEstimateCopyQty().equals(other.getEstimateCopyQty()))
            && (this.getActualCopyQty() == null ? other.getActualCopyQty() == null : this.getActualCopyQty().equals(other.getActualCopyQty()))
            && (this.getCopyStatus() == null ? other.getCopyStatus() == null : this.getCopyStatus().equals(other.getCopyStatus()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culturalreliccopy
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCulturalreliccopyid() == null) ? 0 : getCulturalreliccopyid().hashCode());
        result = prime * result + ((getOutvoucherId() == null) ? 0 : getOutvoucherId().hashCode());
        result = prime * result + ((getCopyType() == null) ? 0 : getCopyType().hashCode());
        result = prime * result + ((getCulid() == null) ? 0 : getCulid().hashCode());
        result = prime * result + ((getCopyDate() == null) ? 0 : getCopyDate().hashCode());
        result = prime * result + ((getCopyMan() == null) ? 0 : getCopyMan().hashCode());
        result = prime * result + ((getCopyPurpose() == null) ? 0 : getCopyPurpose().hashCode());
        result = prime * result + ((getEstimateCopyQty() == null) ? 0 : getEstimateCopyQty().hashCode());
        result = prime * result + ((getActualCopyQty() == null) ? 0 : getActualCopyQty().hashCode());
        result = prime * result + ((getCopyStatus() == null) ? 0 : getCopyStatus().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}