package com.museum.model;

import java.io.Serializable;
import java.util.Date;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table message_inbox
 *
 * @mbg.generated do_not_delete_during_merge Wed Jul 05 16:59:47 CST 2017
 */
public class MessageInbox extends BaseModel implements Serializable {
	/**
	 * Database Column Remarks: 主键
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String id;

	/**
	 * Database Column Remarks: 消息发送者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String fromUserId;

	/**
	 * Database Column Remarks: 消息接收者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String toUserId;

	private String fromName;
	private String toName;
	/**
	 * Database Column Remarks: 消息内容
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String content;

	/**
	 * Database Column Remarks: 是否已读
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.is_read
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private int isRead;

	/**
	 * Database Column Remarks: 消息发送日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private Date createDate;

	/**
	 * 消息删除标志
	 */
	private int isDel;

	/**
	 * Database Column Remarks: 消息类型
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.type
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private int type;

	/**
	 * Database Column Remarks: 针对每一次消息对话，生成的id，目前只针对预约
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String sessionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table message_inbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.id
	 *
	 * @return the value of message_inbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.id
	 *
	 * @param id
	 *            the value for message_inbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.from_user_id
	 *
	 * @return the value of message_inbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getFromUserId() {
		return fromUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.from_user_id
	 *
	 * @param fromUserId
	 *            the value for message_inbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setFromUserId(String fromUserId) {
		this.fromUserId = fromUserId == null ? null : fromUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.to_user_id
	 *
	 * @return the value of message_inbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getToUserId() {
		return toUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.to_user_id
	 *
	 * @param toUserId
	 *            the value for message_inbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setToUserId(String toUserId) {
		this.toUserId = toUserId == null ? null : toUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.content
	 *
	 * @return the value of message_inbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.content
	 *
	 * @param content
	 *            the value for message_inbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.create_date
	 *
	 * @return the value of message_inbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.create_date
	 *
	 * @param createDate
	 *            the value for message_inbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public int getIsRead() {
		return isRead;
	}

	public void setIsRead(int isRead) {
		this.isRead = isRead;
	}

	public int getIsDel() {
		return isDel;
	}

	public void setIsDel(int isDel) {
		this.isDel = isDel;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_inbox.session_id
	 *
	 * @return the value of message_inbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_inbox.session_id
	 *
	 * @param sessionId
	 *            the value for message_inbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId == null ? null : sessionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_inbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public Object getPrimaryKey() {
		return this.getId();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_inbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", fromUserId=").append(fromUserId);
		sb.append(", toUserId=").append(toUserId);
		sb.append(", content=").append(content);
		sb.append(", isRead=").append(isRead);
		sb.append(", createDate=").append(createDate);
		sb.append(", type=").append(type);
		sb.append(", sessionId=").append(sessionId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public String getToName() {
		return toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	public String getFromName() {
		return fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((content == null) ? 0 : content.hashCode());
		result = prime * result
				+ ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result
				+ ((fromName == null) ? 0 : fromName.hashCode());
		result = prime * result
				+ ((fromUserId == null) ? 0 : fromUserId.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + isDel;
		result = prime * result + isRead;
		result = prime * result
				+ ((sessionId == null) ? 0 : sessionId.hashCode());
		result = prime * result + ((toName == null) ? 0 : toName.hashCode());
		result = prime * result
				+ ((toUserId == null) ? 0 : toUserId.hashCode());
		result = prime * result + type;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		MessageInbox other = (MessageInbox) obj;
		if (content == null) {
			if (other.content != null)
				return false;
		} else if (!content.equals(other.content))
			return false;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (fromName == null) {
			if (other.fromName != null)
				return false;
		} else if (!fromName.equals(other.fromName))
			return false;
		if (fromUserId == null) {
			if (other.fromUserId != null)
				return false;
		} else if (!fromUserId.equals(other.fromUserId))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (isDel != other.isDel)
			return false;
		if (isRead != other.isRead)
			return false;
		if (sessionId == null) {
			if (other.sessionId != null)
				return false;
		} else if (!sessionId.equals(other.sessionId))
			return false;
		if (toName == null) {
			if (other.toName != null)
				return false;
		} else if (!toName.equals(other.toName))
			return false;
		if (toUserId == null) {
			if (other.toUserId != null)
				return false;
		} else if (!toUserId.equals(other.toUserId))
			return false;
		if (type != other.type)
			return false;
		return true;
	}

}