package com.museum.model;

import java.io.Serializable;
import java.util.Date;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table message_outbox
 *
 * @mbg.generated do_not_delete_during_merge Wed Jul 05 16:59:47 CST 2017
 */
public class MessageOutbox extends BaseModel implements Serializable {
	/**
	 * Database Column Remarks: 主键
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String id;

	/**
	 * Database Column Remarks: 消息发送者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String fromUserId;

	/**
	 * Database Column Remarks: 消息接收者
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String toUserId;

	private String fromName;
	private String toName;
	/**
	 * Database Column Remarks: 消息内容
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String content;

	/**
	 * Database Column Remarks: 消息发送日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private Date createDate;

	/**
	 * Database Column Remarks: 消息类型 0 缺省消息类型，1目前为预约类型,2、系统消息，当为1时sessionid不为空
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.type
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private Boolean type;

	/**
	 * Database Column Remarks: 是否已读
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_inbox.is_read
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private int isRead;

	/**
	 * Database Column Remarks: 针对每一次消息对话，生成的id，目前只针对预约
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column message_outbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private String sessionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table message_outbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.id
	 *
	 * @return the value of message_outbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.id
	 *
	 * @param id
	 *            the value for message_outbox.id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.from_user_id
	 *
	 * @return the value of message_outbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getFromUserId() {
		return fromUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.from_user_id
	 *
	 * @param fromUserId
	 *            the value for message_outbox.from_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setFromUserId(String fromUserId) {
		this.fromUserId = fromUserId == null ? null : fromUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.to_user_id
	 *
	 * @return the value of message_outbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getToUserId() {
		return toUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.to_user_id
	 *
	 * @param toUserId
	 *            the value for message_outbox.to_user_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setToUserId(String toUserId) {
		this.toUserId = toUserId == null ? null : toUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.content
	 *
	 * @return the value of message_outbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.content
	 *
	 * @param content
	 *            the value for message_outbox.content
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.create_date
	 *
	 * @return the value of message_outbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.create_date
	 *
	 * @param createDate
	 *            the value for message_outbox.create_date
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.type
	 *
	 * @return the value of message_outbox.type
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public Boolean getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.type
	 *
	 * @param type
	 *            the value for message_outbox.type
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setType(Boolean type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column message_outbox.session_id
	 *
	 * @return the value of message_outbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column message_outbox.session_id
	 *
	 * @param sessionId
	 *            the value for message_outbox.session_id
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId == null ? null : sessionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_outbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public Object getPrimaryKey() {
		return this.getId();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_outbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", fromUserId=").append(fromUserId);
		sb.append(", toUserId=").append(toUserId);
		sb.append(", content=").append(content);
		sb.append(", createDate=").append(createDate);
		sb.append(", type=").append(type);
		sb.append(", sessionId=").append(sessionId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_outbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		MessageOutbox other = (MessageOutbox) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getFromUserId() == null ? other.getFromUserId() == null
						: this.getFromUserId().equals(other.getFromUserId()))
				&& (this.getToUserId() == null ? other.getToUserId() == null
						: this.getToUserId().equals(other.getToUserId()))
				&& (this.getContent() == null ? other.getContent() == null
						: this.getContent().equals(other.getContent()))
				&& (this.getCreateDate() == null ? other.getCreateDate() == null
						: this.getCreateDate().equals(other.getCreateDate()))
				&& (this.getType() == null ? other.getType() == null : this
						.getType().equals(other.getType()))
				&& (this.getSessionId() == null ? other.getSessionId() == null
						: this.getSessionId().equals(other.getSessionId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table message_outbox
	 *
	 * @mbg.generated Wed Jul 05 16:59:47 CST 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getFromUserId() == null) ? 0 : getFromUserId().hashCode());
		result = prime * result
				+ ((getToUserId() == null) ? 0 : getToUserId().hashCode());
		result = prime * result
				+ ((getContent() == null) ? 0 : getContent().hashCode());
		result = prime * result
				+ ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
		result = prime * result
				+ ((getType() == null) ? 0 : getType().hashCode());
		result = prime * result
				+ ((getSessionId() == null) ? 0 : getSessionId().hashCode());
		return result;
	}

	public String getFromName() {
		return fromName;
	}

	public void setFromName(String fromName) {
		this.fromName = fromName;
	}

	public String getToName() {
		return toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	public int getIsRead() {
		return isRead;
	}

	public void setIsRead(int isRead) {
		this.isRead = isRead;
	}
}