package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table restorationinfo
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class Restorationinfo extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   修复ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RestorationInfoID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationinfoid;

    /**
     * Database Column Remarks:
     *   档案号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RestorationFileNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationfileno;

    /**
     * Database Column Remarks:
     *   作为逻辑外键，与出库凭证表 Cul_OVMain 的 OutVoucher_ID 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.OutVoucher_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String outvoucherId;

    /**
     * Database Column Remarks:
     *   从文物基础表 Cul_MainCul1/2/3（文物一、二、三）中提取文物信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String culid;

    /**
     * Database Column Remarks:
     *   破损情况/残损情况，由出库凭证形成修复任务档案后，需立即填写，然后才能编辑修复方案。另外，该项用于在回执单中显示“文物残损情况”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Actuality
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String actuality;

    /**
     * Database Column Remarks:
     *   1:内修，2:外修。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RestorationType
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationtype;

    /**
     * Database Column Remarks:
     *   来自于出库凭证的出库日期，作为开始的修复日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Distill_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String distillDate;

    /**
     * Database Column Remarks:
     *   要达到的标准，由出库凭证形成修复任务档案后，需立即填写，然后才能编辑修复方案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Desire
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restDesire;

    /**
     * Database Column Remarks:
     *   由出库凭证形成修复任务档案后，需立即填写，然后才能编辑修复方案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_History
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restHistory;

    /**
     * Database Column Remarks:
     *   与系统代码表 Sys_Code 的 Code 关联，其 CodeType ='RepairGroup'，Superior_Code <> 'xxx'
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Group
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restGroup;

    /**
     * Database Column Remarks:
     *   文物的数量限制，文物一般为一套几件等，这里指具体数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Count
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restCount;

    /**
     * Database Column Remarks:
     *   建档日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.DATEFILE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date datefile;

    /**
     * Database Column Remarks:
     *   归库日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RETURNDATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date returndate;

    /**
     * Database Column Remarks:
     *   修复开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.REPAIRBEGINTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date repairbegintime;

    /**
     * Database Column Remarks:
     *   修复结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.REPAIRENDTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private Date repairendtime;

    /**
     * Database Column Remarks:
     *   外修业务时使用，指总体修复造价，仅接收数字0至9、小数点（小数点后2位）的组合
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Assessment
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String assessment;

    /**
     * Database Column Remarks:
     *   外修业务时使用，指修复周期天数(手工单据中的“修复时间”)，仅接收数字0至9的组合。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Period
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restPeriod;

    /**
     * Database Column Remarks:
     *   外修业务时使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Expert_Signature
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String expertSignature;

    /**
     * Database Column Remarks:
     *   根据修复回执单的“修复方法”进行调整编辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Course
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restCourse;

    /**
     * Database Column Remarks:
     *   修复主持人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_PEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restPeople;

    /**
     * Database Column Remarks:
     *   参与修复人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_PERSONNEL
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restPersonnel;

    /**
     * Database Column Remarks:
     *   验收情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.ACCEPTANCESITU
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String acceptancesitu;

    /**
     * Database Column Remarks:
     *   验收人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.ACCEPTANCEPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String acceptancepeople;

    /**
     * Database Column Remarks:
     *   文物交接人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RELICSHANPER
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String relicshanper;

    /**
     * Database Column Remarks:
     *   文物破损程度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.RELICSDAMEX
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String relicsdamex;

    /**
     * Database Column Remarks:
     *   根据修复回执单的“验收结果”进行调整编辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restCheckout;

    /**
     * Database Column Remarks:
     *   1:待修复，2:已修复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restStatus;

    /**
     * Database Column Remarks:
     *   修复方案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restProject;

    /**
     * Database Column Remarks:
     *   修复备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Rest_remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restRemark;

    /**
     * Database Column Remarks:
     *   建档人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.KEEPPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String keeppeople;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restorationinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RestorationInfoID
     *
     * @return the value of restorationinfo.RestorationInfoID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationinfoid() {
        return restorationinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RestorationInfoID
     *
     * @param restorationinfoid the value for restorationinfo.RestorationInfoID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationinfoid(String restorationinfoid) {
        this.restorationinfoid = restorationinfoid == null ? null : restorationinfoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RestorationFileNo
     *
     * @return the value of restorationinfo.RestorationFileNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationfileno() {
        return restorationfileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RestorationFileNo
     *
     * @param restorationfileno the value for restorationinfo.RestorationFileNo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationfileno(String restorationfileno) {
        this.restorationfileno = restorationfileno == null ? null : restorationfileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.OutVoucher_ID
     *
     * @return the value of restorationinfo.OutVoucher_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getOutvoucherId() {
        return outvoucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.OutVoucher_ID
     *
     * @param outvoucherId the value for restorationinfo.OutVoucher_ID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setOutvoucherId(String outvoucherId) {
        this.outvoucherId = outvoucherId == null ? null : outvoucherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.CulID
     *
     * @return the value of restorationinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCulid() {
        return culid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.CulID
     *
     * @param culid the value for restorationinfo.CulID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCulid(String culid) {
        this.culid = culid == null ? null : culid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Actuality
     *
     * @return the value of restorationinfo.Actuality
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getActuality() {
        return actuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Actuality
     *
     * @param actuality the value for restorationinfo.Actuality
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setActuality(String actuality) {
        this.actuality = actuality == null ? null : actuality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RestorationType
     *
     * @return the value of restorationinfo.RestorationType
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationtype() {
        return restorationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RestorationType
     *
     * @param restorationtype the value for restorationinfo.RestorationType
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationtype(String restorationtype) {
        this.restorationtype = restorationtype == null ? null : restorationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Distill_Date
     *
     * @return the value of restorationinfo.Distill_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getDistillDate() {
        return distillDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Distill_Date
     *
     * @param distillDate the value for restorationinfo.Distill_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setDistillDate(String distillDate) {
        this.distillDate = distillDate == null ? null : distillDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Desire
     *
     * @return the value of restorationinfo.Rest_Desire
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestDesire() {
        return restDesire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Desire
     *
     * @param restDesire the value for restorationinfo.Rest_Desire
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestDesire(String restDesire) {
        this.restDesire = restDesire == null ? null : restDesire.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_History
     *
     * @return the value of restorationinfo.Rest_History
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestHistory() {
        return restHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_History
     *
     * @param restHistory the value for restorationinfo.Rest_History
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestHistory(String restHistory) {
        this.restHistory = restHistory == null ? null : restHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Group
     *
     * @return the value of restorationinfo.Rest_Group
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestGroup() {
        return restGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Group
     *
     * @param restGroup the value for restorationinfo.Rest_Group
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestGroup(String restGroup) {
        this.restGroup = restGroup == null ? null : restGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Count
     *
     * @return the value of restorationinfo.Rest_Count
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestCount() {
        return restCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Count
     *
     * @param restCount the value for restorationinfo.Rest_Count
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestCount(String restCount) {
        this.restCount = restCount == null ? null : restCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.DATEFILE
     *
     * @return the value of restorationinfo.DATEFILE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getDatefile() {
        return datefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.DATEFILE
     *
     * @param datefile the value for restorationinfo.DATEFILE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setDatefile(Date datefile) {
        this.datefile = datefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RETURNDATE
     *
     * @return the value of restorationinfo.RETURNDATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RETURNDATE
     *
     * @param returndate the value for restorationinfo.RETURNDATE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.REPAIRBEGINTIME
     *
     * @return the value of restorationinfo.REPAIRBEGINTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getRepairbegintime() {
        return repairbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.REPAIRBEGINTIME
     *
     * @param repairbegintime the value for restorationinfo.REPAIRBEGINTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRepairbegintime(Date repairbegintime) {
        this.repairbegintime = repairbegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.REPAIRENDTIME
     *
     * @return the value of restorationinfo.REPAIRENDTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public Date getRepairendtime() {
        return repairendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.REPAIRENDTIME
     *
     * @param repairendtime the value for restorationinfo.REPAIRENDTIME
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRepairendtime(Date repairendtime) {
        this.repairendtime = repairendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Assessment
     *
     * @return the value of restorationinfo.Assessment
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAssessment() {
        return assessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Assessment
     *
     * @param assessment the value for restorationinfo.Assessment
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAssessment(String assessment) {
        this.assessment = assessment == null ? null : assessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Period
     *
     * @return the value of restorationinfo.Rest_Period
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestPeriod() {
        return restPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Period
     *
     * @param restPeriod the value for restorationinfo.Rest_Period
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestPeriod(String restPeriod) {
        this.restPeriod = restPeriod == null ? null : restPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Expert_Signature
     *
     * @return the value of restorationinfo.Expert_Signature
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getExpertSignature() {
        return expertSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Expert_Signature
     *
     * @param expertSignature the value for restorationinfo.Expert_Signature
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setExpertSignature(String expertSignature) {
        this.expertSignature = expertSignature == null ? null : expertSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Course
     *
     * @return the value of restorationinfo.Rest_Course
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestCourse() {
        return restCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Course
     *
     * @param restCourse the value for restorationinfo.Rest_Course
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestCourse(String restCourse) {
        this.restCourse = restCourse == null ? null : restCourse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_PEOPLE
     *
     * @return the value of restorationinfo.Rest_PEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestPeople() {
        return restPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_PEOPLE
     *
     * @param restPeople the value for restorationinfo.Rest_PEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestPeople(String restPeople) {
        this.restPeople = restPeople == null ? null : restPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_PERSONNEL
     *
     * @return the value of restorationinfo.Rest_PERSONNEL
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestPersonnel() {
        return restPersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_PERSONNEL
     *
     * @param restPersonnel the value for restorationinfo.Rest_PERSONNEL
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestPersonnel(String restPersonnel) {
        this.restPersonnel = restPersonnel == null ? null : restPersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.ACCEPTANCESITU
     *
     * @return the value of restorationinfo.ACCEPTANCESITU
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAcceptancesitu() {
        return acceptancesitu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.ACCEPTANCESITU
     *
     * @param acceptancesitu the value for restorationinfo.ACCEPTANCESITU
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAcceptancesitu(String acceptancesitu) {
        this.acceptancesitu = acceptancesitu == null ? null : acceptancesitu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.ACCEPTANCEPEOPLE
     *
     * @return the value of restorationinfo.ACCEPTANCEPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAcceptancepeople() {
        return acceptancepeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.ACCEPTANCEPEOPLE
     *
     * @param acceptancepeople the value for restorationinfo.ACCEPTANCEPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAcceptancepeople(String acceptancepeople) {
        this.acceptancepeople = acceptancepeople == null ? null : acceptancepeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RELICSHANPER
     *
     * @return the value of restorationinfo.RELICSHANPER
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRelicshanper() {
        return relicshanper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RELICSHANPER
     *
     * @param relicshanper the value for restorationinfo.RELICSHANPER
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRelicshanper(String relicshanper) {
        this.relicshanper = relicshanper == null ? null : relicshanper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.RELICSDAMEX
     *
     * @return the value of restorationinfo.RELICSDAMEX
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRelicsdamex() {
        return relicsdamex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.RELICSDAMEX
     *
     * @param relicsdamex the value for restorationinfo.RELICSDAMEX
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRelicsdamex(String relicsdamex) {
        this.relicsdamex = relicsdamex == null ? null : relicsdamex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Checkout
     *
     * @return the value of restorationinfo.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestCheckout() {
        return restCheckout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Checkout
     *
     * @param restCheckout the value for restorationinfo.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestCheckout(String restCheckout) {
        this.restCheckout = restCheckout == null ? null : restCheckout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_Status
     *
     * @return the value of restorationinfo.Rest_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestStatus() {
        return restStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_Status
     *
     * @param restStatus the value for restorationinfo.Rest_Status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestStatus(String restStatus) {
        this.restStatus = restStatus == null ? null : restStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_project
     *
     * @return the value of restorationinfo.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestProject() {
        return restProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_project
     *
     * @param restProject the value for restorationinfo.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestProject(String restProject) {
        this.restProject = restProject == null ? null : restProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Rest_remark
     *
     * @return the value of restorationinfo.Rest_remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestRemark() {
        return restRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Rest_remark
     *
     * @param restRemark the value for restorationinfo.Rest_remark
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestRemark(String restRemark) {
        this.restRemark = restRemark == null ? null : restRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.KEEPPEOPLE
     *
     * @return the value of restorationinfo.KEEPPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getKeeppeople() {
        return keeppeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.KEEPPEOPLE
     *
     * @param keeppeople the value for restorationinfo.KEEPPEOPLE
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setKeeppeople(String keeppeople) {
        this.keeppeople = keeppeople == null ? null : keeppeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Updating_UID
     *
     * @return the value of restorationinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Updating_UID
     *
     * @param updatingUid the value for restorationinfo.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationinfo.Updating_Date
     *
     * @return the value of restorationinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationinfo.Updating_Date
     *
     * @param updatingDate the value for restorationinfo.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getRestorationinfoid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", restorationinfoid=").append(restorationinfoid);
        sb.append(", restorationfileno=").append(restorationfileno);
        sb.append(", outvoucherId=").append(outvoucherId);
        sb.append(", culid=").append(culid);
        sb.append(", actuality=").append(actuality);
        sb.append(", restorationtype=").append(restorationtype);
        sb.append(", distillDate=").append(distillDate);
        sb.append(", restDesire=").append(restDesire);
        sb.append(", restHistory=").append(restHistory);
        sb.append(", restGroup=").append(restGroup);
        sb.append(", restCount=").append(restCount);
        sb.append(", datefile=").append(datefile);
        sb.append(", returndate=").append(returndate);
        sb.append(", repairbegintime=").append(repairbegintime);
        sb.append(", repairendtime=").append(repairendtime);
        sb.append(", assessment=").append(assessment);
        sb.append(", restPeriod=").append(restPeriod);
        sb.append(", expertSignature=").append(expertSignature);
        sb.append(", restCourse=").append(restCourse);
        sb.append(", restPeople=").append(restPeople);
        sb.append(", restPersonnel=").append(restPersonnel);
        sb.append(", acceptancesitu=").append(acceptancesitu);
        sb.append(", acceptancepeople=").append(acceptancepeople);
        sb.append(", relicshanper=").append(relicshanper);
        sb.append(", relicsdamex=").append(relicsdamex);
        sb.append(", restCheckout=").append(restCheckout);
        sb.append(", restStatus=").append(restStatus);
        sb.append(", restProject=").append(restProject);
        sb.append(", restRemark=").append(restRemark);
        sb.append(", keeppeople=").append(keeppeople);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Restorationinfo other = (Restorationinfo) that;
        return (this.getRestorationinfoid() == null ? other.getRestorationinfoid() == null : this.getRestorationinfoid().equals(other.getRestorationinfoid()))
            && (this.getRestorationfileno() == null ? other.getRestorationfileno() == null : this.getRestorationfileno().equals(other.getRestorationfileno()))
            && (this.getOutvoucherId() == null ? other.getOutvoucherId() == null : this.getOutvoucherId().equals(other.getOutvoucherId()))
            && (this.getCulid() == null ? other.getCulid() == null : this.getCulid().equals(other.getCulid()))
            && (this.getActuality() == null ? other.getActuality() == null : this.getActuality().equals(other.getActuality()))
            && (this.getRestorationtype() == null ? other.getRestorationtype() == null : this.getRestorationtype().equals(other.getRestorationtype()))
            && (this.getDistillDate() == null ? other.getDistillDate() == null : this.getDistillDate().equals(other.getDistillDate()))
            && (this.getRestDesire() == null ? other.getRestDesire() == null : this.getRestDesire().equals(other.getRestDesire()))
            && (this.getRestHistory() == null ? other.getRestHistory() == null : this.getRestHistory().equals(other.getRestHistory()))
            && (this.getRestGroup() == null ? other.getRestGroup() == null : this.getRestGroup().equals(other.getRestGroup()))
            && (this.getRestCount() == null ? other.getRestCount() == null : this.getRestCount().equals(other.getRestCount()))
            && (this.getDatefile() == null ? other.getDatefile() == null : this.getDatefile().equals(other.getDatefile()))
            && (this.getReturndate() == null ? other.getReturndate() == null : this.getReturndate().equals(other.getReturndate()))
            && (this.getRepairbegintime() == null ? other.getRepairbegintime() == null : this.getRepairbegintime().equals(other.getRepairbegintime()))
            && (this.getRepairendtime() == null ? other.getRepairendtime() == null : this.getRepairendtime().equals(other.getRepairendtime()))
            && (this.getAssessment() == null ? other.getAssessment() == null : this.getAssessment().equals(other.getAssessment()))
            && (this.getRestPeriod() == null ? other.getRestPeriod() == null : this.getRestPeriod().equals(other.getRestPeriod()))
            && (this.getExpertSignature() == null ? other.getExpertSignature() == null : this.getExpertSignature().equals(other.getExpertSignature()))
            && (this.getRestCourse() == null ? other.getRestCourse() == null : this.getRestCourse().equals(other.getRestCourse()))
            && (this.getRestPeople() == null ? other.getRestPeople() == null : this.getRestPeople().equals(other.getRestPeople()))
            && (this.getRestPersonnel() == null ? other.getRestPersonnel() == null : this.getRestPersonnel().equals(other.getRestPersonnel()))
            && (this.getAcceptancesitu() == null ? other.getAcceptancesitu() == null : this.getAcceptancesitu().equals(other.getAcceptancesitu()))
            && (this.getAcceptancepeople() == null ? other.getAcceptancepeople() == null : this.getAcceptancepeople().equals(other.getAcceptancepeople()))
            && (this.getRelicshanper() == null ? other.getRelicshanper() == null : this.getRelicshanper().equals(other.getRelicshanper()))
            && (this.getRelicsdamex() == null ? other.getRelicsdamex() == null : this.getRelicsdamex().equals(other.getRelicsdamex()))
            && (this.getRestCheckout() == null ? other.getRestCheckout() == null : this.getRestCheckout().equals(other.getRestCheckout()))
            && (this.getRestStatus() == null ? other.getRestStatus() == null : this.getRestStatus().equals(other.getRestStatus()))
            && (this.getRestProject() == null ? other.getRestProject() == null : this.getRestProject().equals(other.getRestProject()))
            && (this.getRestRemark() == null ? other.getRestRemark() == null : this.getRestRemark().equals(other.getRestRemark()))
            && (this.getKeeppeople() == null ? other.getKeeppeople() == null : this.getKeeppeople().equals(other.getKeeppeople()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationinfo
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRestorationinfoid() == null) ? 0 : getRestorationinfoid().hashCode());
        result = prime * result + ((getRestorationfileno() == null) ? 0 : getRestorationfileno().hashCode());
        result = prime * result + ((getOutvoucherId() == null) ? 0 : getOutvoucherId().hashCode());
        result = prime * result + ((getCulid() == null) ? 0 : getCulid().hashCode());
        result = prime * result + ((getActuality() == null) ? 0 : getActuality().hashCode());
        result = prime * result + ((getRestorationtype() == null) ? 0 : getRestorationtype().hashCode());
        result = prime * result + ((getDistillDate() == null) ? 0 : getDistillDate().hashCode());
        result = prime * result + ((getRestDesire() == null) ? 0 : getRestDesire().hashCode());
        result = prime * result + ((getRestHistory() == null) ? 0 : getRestHistory().hashCode());
        result = prime * result + ((getRestGroup() == null) ? 0 : getRestGroup().hashCode());
        result = prime * result + ((getRestCount() == null) ? 0 : getRestCount().hashCode());
        result = prime * result + ((getDatefile() == null) ? 0 : getDatefile().hashCode());
        result = prime * result + ((getReturndate() == null) ? 0 : getReturndate().hashCode());
        result = prime * result + ((getRepairbegintime() == null) ? 0 : getRepairbegintime().hashCode());
        result = prime * result + ((getRepairendtime() == null) ? 0 : getRepairendtime().hashCode());
        result = prime * result + ((getAssessment() == null) ? 0 : getAssessment().hashCode());
        result = prime * result + ((getRestPeriod() == null) ? 0 : getRestPeriod().hashCode());
        result = prime * result + ((getExpertSignature() == null) ? 0 : getExpertSignature().hashCode());
        result = prime * result + ((getRestCourse() == null) ? 0 : getRestCourse().hashCode());
        result = prime * result + ((getRestPeople() == null) ? 0 : getRestPeople().hashCode());
        result = prime * result + ((getRestPersonnel() == null) ? 0 : getRestPersonnel().hashCode());
        result = prime * result + ((getAcceptancesitu() == null) ? 0 : getAcceptancesitu().hashCode());
        result = prime * result + ((getAcceptancepeople() == null) ? 0 : getAcceptancepeople().hashCode());
        result = prime * result + ((getRelicshanper() == null) ? 0 : getRelicshanper().hashCode());
        result = prime * result + ((getRelicsdamex() == null) ? 0 : getRelicsdamex().hashCode());
        result = prime * result + ((getRestCheckout() == null) ? 0 : getRestCheckout().hashCode());
        result = prime * result + ((getRestStatus() == null) ? 0 : getRestStatus().hashCode());
        result = prime * result + ((getRestProject() == null) ? 0 : getRestProject().hashCode());
        result = prime * result + ((getRestRemark() == null) ? 0 : getRestRemark().hashCode());
        result = prime * result + ((getKeeppeople() == null) ? 0 : getKeeppeople().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}