package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table restorationproject
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class Restorationproject extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   修复方案ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.RestorationProjectid
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationprojectid;

    /**
     * Database Column Remarks:
     *   主持人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String compere;

    /**
     * Database Column Remarks:
     *   预计修复人，用于修复回执单、修复档案中的实际修复人的编辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Rest_person
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restPerson;

    /**
     * Database Column Remarks:
     *   方案制定人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Rest_project_framer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restProjectFramer;

    /**
     * Database Column Remarks:
     *   方案审定人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Rest_project_assessor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restProjectAssessor;

    /**
     * Database Column Remarks:
     *   领导审批
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.director
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String director;

    /**
     * Database Column Remarks:
     *   领导审批
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.curator
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String curator;

    /**
     * Database Column Remarks:
     *   修复方案内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restProject;

    /**
     * Database Column Remarks:
     *   使用材料
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Adoptive_Material
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String adoptiveMaterial;

    /**
     * Database Column Remarks:
     *   1:未审批，2:审批通过，3:审批未通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Rest_status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restStatus;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationproject.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restorationproject
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.RestorationProjectid
     *
     * @return the value of restorationproject.RestorationProjectid
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationprojectid() {
        return restorationprojectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.RestorationProjectid
     *
     * @param restorationprojectid the value for restorationproject.RestorationProjectid
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationprojectid(String restorationprojectid) {
        this.restorationprojectid = restorationprojectid == null ? null : restorationprojectid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.compere
     *
     * @return the value of restorationproject.compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCompere() {
        return compere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.compere
     *
     * @param compere the value for restorationproject.compere
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCompere(String compere) {
        this.compere = compere == null ? null : compere.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Rest_person
     *
     * @return the value of restorationproject.Rest_person
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestPerson() {
        return restPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Rest_person
     *
     * @param restPerson the value for restorationproject.Rest_person
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestPerson(String restPerson) {
        this.restPerson = restPerson == null ? null : restPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Rest_project_framer
     *
     * @return the value of restorationproject.Rest_project_framer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestProjectFramer() {
        return restProjectFramer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Rest_project_framer
     *
     * @param restProjectFramer the value for restorationproject.Rest_project_framer
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestProjectFramer(String restProjectFramer) {
        this.restProjectFramer = restProjectFramer == null ? null : restProjectFramer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Rest_project_assessor
     *
     * @return the value of restorationproject.Rest_project_assessor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestProjectAssessor() {
        return restProjectAssessor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Rest_project_assessor
     *
     * @param restProjectAssessor the value for restorationproject.Rest_project_assessor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestProjectAssessor(String restProjectAssessor) {
        this.restProjectAssessor = restProjectAssessor == null ? null : restProjectAssessor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.director
     *
     * @return the value of restorationproject.director
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.director
     *
     * @param director the value for restorationproject.director
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.curator
     *
     * @return the value of restorationproject.curator
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCurator() {
        return curator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.curator
     *
     * @param curator the value for restorationproject.curator
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCurator(String curator) {
        this.curator = curator == null ? null : curator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Rest_project
     *
     * @return the value of restorationproject.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestProject() {
        return restProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Rest_project
     *
     * @param restProject the value for restorationproject.Rest_project
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestProject(String restProject) {
        this.restProject = restProject == null ? null : restProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Adoptive_Material
     *
     * @return the value of restorationproject.Adoptive_Material
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getAdoptiveMaterial() {
        return adoptiveMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Adoptive_Material
     *
     * @param adoptiveMaterial the value for restorationproject.Adoptive_Material
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setAdoptiveMaterial(String adoptiveMaterial) {
        this.adoptiveMaterial = adoptiveMaterial == null ? null : adoptiveMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Rest_status
     *
     * @return the value of restorationproject.Rest_status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestStatus() {
        return restStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Rest_status
     *
     * @param restStatus the value for restorationproject.Rest_status
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestStatus(String restStatus) {
        this.restStatus = restStatus == null ? null : restStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Updating_UID
     *
     * @return the value of restorationproject.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Updating_UID
     *
     * @param updatingUid the value for restorationproject.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationproject.Updating_Date
     *
     * @return the value of restorationproject.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationproject.Updating_Date
     *
     * @param updatingDate the value for restorationproject.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationproject
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getRestorationprojectid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationproject
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", restorationprojectid=").append(restorationprojectid);
        sb.append(", compere=").append(compere);
        sb.append(", restPerson=").append(restPerson);
        sb.append(", restProjectFramer=").append(restProjectFramer);
        sb.append(", restProjectAssessor=").append(restProjectAssessor);
        sb.append(", director=").append(director);
        sb.append(", curator=").append(curator);
        sb.append(", restProject=").append(restProject);
        sb.append(", adoptiveMaterial=").append(adoptiveMaterial);
        sb.append(", restStatus=").append(restStatus);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationproject
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Restorationproject other = (Restorationproject) that;
        return (this.getRestorationprojectid() == null ? other.getRestorationprojectid() == null : this.getRestorationprojectid().equals(other.getRestorationprojectid()))
            && (this.getCompere() == null ? other.getCompere() == null : this.getCompere().equals(other.getCompere()))
            && (this.getRestPerson() == null ? other.getRestPerson() == null : this.getRestPerson().equals(other.getRestPerson()))
            && (this.getRestProjectFramer() == null ? other.getRestProjectFramer() == null : this.getRestProjectFramer().equals(other.getRestProjectFramer()))
            && (this.getRestProjectAssessor() == null ? other.getRestProjectAssessor() == null : this.getRestProjectAssessor().equals(other.getRestProjectAssessor()))
            && (this.getDirector() == null ? other.getDirector() == null : this.getDirector().equals(other.getDirector()))
            && (this.getCurator() == null ? other.getCurator() == null : this.getCurator().equals(other.getCurator()))
            && (this.getRestProject() == null ? other.getRestProject() == null : this.getRestProject().equals(other.getRestProject()))
            && (this.getAdoptiveMaterial() == null ? other.getAdoptiveMaterial() == null : this.getAdoptiveMaterial().equals(other.getAdoptiveMaterial()))
            && (this.getRestStatus() == null ? other.getRestStatus() == null : this.getRestStatus().equals(other.getRestStatus()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationproject
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRestorationprojectid() == null) ? 0 : getRestorationprojectid().hashCode());
        result = prime * result + ((getCompere() == null) ? 0 : getCompere().hashCode());
        result = prime * result + ((getRestPerson() == null) ? 0 : getRestPerson().hashCode());
        result = prime * result + ((getRestProjectFramer() == null) ? 0 : getRestProjectFramer().hashCode());
        result = prime * result + ((getRestProjectAssessor() == null) ? 0 : getRestProjectAssessor().hashCode());
        result = prime * result + ((getDirector() == null) ? 0 : getDirector().hashCode());
        result = prime * result + ((getCurator() == null) ? 0 : getCurator().hashCode());
        result = prime * result + ((getRestProject() == null) ? 0 : getRestProject().hashCode());
        result = prime * result + ((getAdoptiveMaterial() == null) ? 0 : getAdoptiveMaterial().hashCode());
        result = prime * result + ((getRestStatus() == null) ? 0 : getRestStatus().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}