package com.museum.model;

import com.framework.model.BaseModel;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table restorationreceipt
 *
 * @mbg.generated do_not_delete_during_merge Wed Aug 30 17:15:10 CST 2017
 */
public class Restorationreceipt extends BaseModel implements Serializable {
    /**
     * Database Column Remarks:
     *   修复回执单ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.RestorationReceiptID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationreceiptid;

    /**
     * Database Column Remarks:
     *   实际修复人，参照修复方案中的预计修复人进行编辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.ReceiptPerson
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String receiptperson;

    /**
     * Database Column Remarks:
     *   修复完成后收回验收日期，作为完成的修复日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.Back_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String backDate;

    /**
     * Database Column Remarks:
     *   修复方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.RestorationMethod
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restorationmethod;

    /**
     * Database Column Remarks:
     *   用于显示修复档案的验收人；外修业务时，“验收人”记录“专家签字”
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.Censor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String censor;

    /**
     * Database Column Remarks:
     *   验收结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String restCheckout;

    /**
     * Database Column Remarks:
     *   1:未验收；2:验收通过；3：验收不通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.ReceiptStatus
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String receiptstatus;

    /**
     * Database Column Remarks:
     *   作为业务信息的录入者，与系统用户表 Sys_User 关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingUid;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restorationreceipt.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private String updatingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restorationreceipt
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.RestorationReceiptID
     *
     * @return the value of restorationreceipt.RestorationReceiptID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationreceiptid() {
        return restorationreceiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.RestorationReceiptID
     *
     * @param restorationreceiptid the value for restorationreceipt.RestorationReceiptID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationreceiptid(String restorationreceiptid) {
        this.restorationreceiptid = restorationreceiptid == null ? null : restorationreceiptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.ReceiptPerson
     *
     * @return the value of restorationreceipt.ReceiptPerson
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getReceiptperson() {
        return receiptperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.ReceiptPerson
     *
     * @param receiptperson the value for restorationreceipt.ReceiptPerson
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setReceiptperson(String receiptperson) {
        this.receiptperson = receiptperson == null ? null : receiptperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.Back_Date
     *
     * @return the value of restorationreceipt.Back_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.Back_Date
     *
     * @param backDate the value for restorationreceipt.Back_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setBackDate(String backDate) {
        this.backDate = backDate == null ? null : backDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.RestorationMethod
     *
     * @return the value of restorationreceipt.RestorationMethod
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestorationmethod() {
        return restorationmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.RestorationMethod
     *
     * @param restorationmethod the value for restorationreceipt.RestorationMethod
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestorationmethod(String restorationmethod) {
        this.restorationmethod = restorationmethod == null ? null : restorationmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.Censor
     *
     * @return the value of restorationreceipt.Censor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getCensor() {
        return censor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.Censor
     *
     * @param censor the value for restorationreceipt.Censor
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setCensor(String censor) {
        this.censor = censor == null ? null : censor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.Rest_Checkout
     *
     * @return the value of restorationreceipt.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getRestCheckout() {
        return restCheckout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.Rest_Checkout
     *
     * @param restCheckout the value for restorationreceipt.Rest_Checkout
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setRestCheckout(String restCheckout) {
        this.restCheckout = restCheckout == null ? null : restCheckout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.ReceiptStatus
     *
     * @return the value of restorationreceipt.ReceiptStatus
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getReceiptstatus() {
        return receiptstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.ReceiptStatus
     *
     * @param receiptstatus the value for restorationreceipt.ReceiptStatus
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setReceiptstatus(String receiptstatus) {
        this.receiptstatus = receiptstatus == null ? null : receiptstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.Updating_UID
     *
     * @return the value of restorationreceipt.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingUid() {
        return updatingUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.Updating_UID
     *
     * @param updatingUid the value for restorationreceipt.Updating_UID
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingUid(String updatingUid) {
        this.updatingUid = updatingUid == null ? null : updatingUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restorationreceipt.Updating_Date
     *
     * @return the value of restorationreceipt.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public String getUpdatingDate() {
        return updatingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restorationreceipt.Updating_Date
     *
     * @param updatingDate the value for restorationreceipt.Updating_Date
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    public void setUpdatingDate(String updatingDate) {
        this.updatingDate = updatingDate == null ? null : updatingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationreceipt
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public Object getPrimaryKey() {
        return this.getRestorationreceiptid();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationreceipt
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", restorationreceiptid=").append(restorationreceiptid);
        sb.append(", receiptperson=").append(receiptperson);
        sb.append(", backDate=").append(backDate);
        sb.append(", restorationmethod=").append(restorationmethod);
        sb.append(", censor=").append(censor);
        sb.append(", restCheckout=").append(restCheckout);
        sb.append(", receiptstatus=").append(receiptstatus);
        sb.append(", updatingUid=").append(updatingUid);
        sb.append(", updatingDate=").append(updatingDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationreceipt
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Restorationreceipt other = (Restorationreceipt) that;
        return (this.getRestorationreceiptid() == null ? other.getRestorationreceiptid() == null : this.getRestorationreceiptid().equals(other.getRestorationreceiptid()))
            && (this.getReceiptperson() == null ? other.getReceiptperson() == null : this.getReceiptperson().equals(other.getReceiptperson()))
            && (this.getBackDate() == null ? other.getBackDate() == null : this.getBackDate().equals(other.getBackDate()))
            && (this.getRestorationmethod() == null ? other.getRestorationmethod() == null : this.getRestorationmethod().equals(other.getRestorationmethod()))
            && (this.getCensor() == null ? other.getCensor() == null : this.getCensor().equals(other.getCensor()))
            && (this.getRestCheckout() == null ? other.getRestCheckout() == null : this.getRestCheckout().equals(other.getRestCheckout()))
            && (this.getReceiptstatus() == null ? other.getReceiptstatus() == null : this.getReceiptstatus().equals(other.getReceiptstatus()))
            && (this.getUpdatingUid() == null ? other.getUpdatingUid() == null : this.getUpdatingUid().equals(other.getUpdatingUid()))
            && (this.getUpdatingDate() == null ? other.getUpdatingDate() == null : this.getUpdatingDate().equals(other.getUpdatingDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restorationreceipt
     *
     * @mbg.generated Wed Aug 30 17:15:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRestorationreceiptid() == null) ? 0 : getRestorationreceiptid().hashCode());
        result = prime * result + ((getReceiptperson() == null) ? 0 : getReceiptperson().hashCode());
        result = prime * result + ((getBackDate() == null) ? 0 : getBackDate().hashCode());
        result = prime * result + ((getRestorationmethod() == null) ? 0 : getRestorationmethod().hashCode());
        result = prime * result + ((getCensor() == null) ? 0 : getCensor().hashCode());
        result = prime * result + ((getRestCheckout() == null) ? 0 : getRestCheckout().hashCode());
        result = prime * result + ((getReceiptstatus() == null) ? 0 : getReceiptstatus().hashCode());
        result = prime * result + ((getUpdatingUid() == null) ? 0 : getUpdatingUid().hashCode());
        result = prime * result + ((getUpdatingDate() == null) ? 0 : getUpdatingDate().hashCode());
        return result;
    }
}