package com.framework.activiti.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table wf_approvalrecord
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 13 16:59:37 CST 2018
 */
public class WFApprovalRecord extends BaseModel implements Serializable {
    /**
     * Database Column Remarks: approvalid
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.APPROVALID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String approvalid;

    /**
     * Database Column Remarks: DeclarationId
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String applicationformid;

    /**
     * Database Column Remarks: 操作人
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.AUDITOR
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String auditor;

    /**
     * Database Column Remarks: 操作人姓名
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.OPERATORNAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String operatorname;

    /**
     * Database Column Remarks: 操作时间
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.OPERTIME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private Date opertime;

    /**
     * Database Column Remarks: 状态
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String status;

    /**
     * Database Column Remarks: 意见
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.APPROVALOPTION
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String approvaloption;

    /**
     * Database Column Remarks: 节点id
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String nodeid;

    /**
     * Database Column Remarks: 节点名
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.NODENAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String nodename;

    /**
     * Database Column Remarks: 备注
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_approvalrecord.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private byte[] remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table wf_approvalrecord
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.APPROVALID
     *
     * @return the value of wf_approvalrecord.APPROVALID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getApprovalid() {
	return approvalid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.APPROVALID
     *
     * @param approvalid
     *            the value for wf_approvalrecord.APPROVALID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setApprovalid(String approvalid) {
	this.approvalid = approvalid == null ? null : approvalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.applicationformid
     *
     * @return the value of wf_approvalrecord.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getApplicationformid() {
	return applicationformid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.applicationformid
     *
     * @param applicationformid
     *            the value for wf_approvalrecord.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setApplicationformid(String applicationformid) {
	this.applicationformid = applicationformid == null ? null : applicationformid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.AUDITOR
     *
     * @return the value of wf_approvalrecord.AUDITOR
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getAuditor() {
	return auditor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.AUDITOR
     *
     * @param auditor
     *            the value for wf_approvalrecord.AUDITOR
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setAuditor(String auditor) {
	this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.OPERATORNAME
     *
     * @return the value of wf_approvalrecord.OPERATORNAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getOperatorname() {
	return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.OPERATORNAME
     *
     * @param operatorname
     *            the value for wf_approvalrecord.OPERATORNAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setOperatorname(String operatorname) {
	this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.OPERTIME
     *
     * @return the value of wf_approvalrecord.OPERTIME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public Date getOpertime() {
	return opertime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.OPERTIME
     *
     * @param opertime
     *            the value for wf_approvalrecord.OPERTIME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setOpertime(Date opertime) {
	this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.STATUS
     *
     * @return the value of wf_approvalrecord.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getStatus() {
	return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.STATUS
     *
     * @param status
     *            the value for wf_approvalrecord.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setStatus(String status) {
	this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.APPROVALOPTION
     *
     * @return the value of wf_approvalrecord.APPROVALOPTION
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getApprovaloption() {
	return approvaloption;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.APPROVALOPTION
     *
     * @param approvaloption
     *            the value for wf_approvalrecord.APPROVALOPTION
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setApprovaloption(String approvaloption) {
	this.approvaloption = approvaloption == null ? null : approvaloption.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.NODEID
     *
     * @return the value of wf_approvalrecord.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getNodeid() {
	return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.NODEID
     *
     * @param nodeid
     *            the value for wf_approvalrecord.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setNodeid(String nodeid) {
	this.nodeid = nodeid == null ? null : nodeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.NODENAME
     *
     * @return the value of wf_approvalrecord.NODENAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getNodename() {
	return nodename;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.NODENAME
     *
     * @param nodename
     *            the value for wf_approvalrecord.NODENAME
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setNodename(String nodename) {
	this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_approvalrecord.REMARK
     *
     * @return the value of wf_approvalrecord.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public byte[] getRemark() {
	return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_approvalrecord.REMARK
     *
     * @param remark
     *            the value for wf_approvalrecord.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setRemark(byte[] remark) {
	this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_approvalrecord
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public Object getPrimaryKey() {
	return this.getApprovalid();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_approvalrecord
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public String toString() {
	StringBuilder sb = new StringBuilder();
	sb.append(getClass().getSimpleName());
	sb.append(" [");
	sb.append("Hash = ").append(hashCode());
	sb.append(", approvalid=").append(approvalid);
	sb.append(", applicationformid=").append(applicationformid);
	sb.append(", auditor=").append(auditor);
	sb.append(", operatorname=").append(operatorname);
	sb.append(", opertime=").append(opertime);
	sb.append(", status=").append(status);
	sb.append(", approvaloption=").append(approvaloption);
	sb.append(", nodeid=").append(nodeid);
	sb.append(", nodename=").append(nodename);
	sb.append(", remark=").append(remark);
	sb.append(", serialVersionUID=").append(serialVersionUID);
	sb.append("]");
	return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_approvalrecord
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public boolean equals(Object that) {
	if (this == that) {
	    return true;
	}
	if (that == null) {
	    return false;
	}
	if (getClass() != that.getClass()) {
	    return false;
	}
	WFApprovalRecord other = (WFApprovalRecord) that;
	return (this.getApprovalid() == null ? other.getApprovalid() == null
		: this.getApprovalid().equals(other.getApprovalid()))
		&& (this.getApplicationformid() == null ? other.getApplicationformid() == null
			: this.getApplicationformid().equals(other.getApplicationformid()))
		&& (this.getAuditor() == null ? other.getAuditor() == null
			: this.getAuditor().equals(other.getAuditor()))
		&& (this.getOperatorname() == null ? other.getOperatorname() == null
			: this.getOperatorname().equals(other.getOperatorname()))
		&& (this.getOpertime() == null ? other.getOpertime() == null
			: this.getOpertime().equals(other.getOpertime()))
		&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
		&& (this.getApprovaloption() == null ? other.getApprovaloption() == null
			: this.getApprovaloption().equals(other.getApprovaloption()))
		&& (this.getNodeid() == null ? other.getNodeid() == null : this.getNodeid().equals(other.getNodeid()))
		&& (this.getNodename() == null ? other.getNodename() == null
			: this.getNodename().equals(other.getNodename()))
		&& (Arrays.equals(this.getRemark(), other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_approvalrecord
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((getApprovalid() == null) ? 0 : getApprovalid().hashCode());
	result = prime * result + ((getApplicationformid() == null) ? 0 : getApplicationformid().hashCode());
	result = prime * result + ((getAuditor() == null) ? 0 : getAuditor().hashCode());
	result = prime * result + ((getOperatorname() == null) ? 0 : getOperatorname().hashCode());
	result = prime * result + ((getOpertime() == null) ? 0 : getOpertime().hashCode());
	result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
	result = prime * result + ((getApprovaloption() == null) ? 0 : getApprovaloption().hashCode());
	result = prime * result + ((getNodeid() == null) ? 0 : getNodeid().hashCode());
	result = prime * result + ((getNodename() == null) ? 0 : getNodename().hashCode());
	result = prime * result + (Arrays.hashCode(getRemark()));
	return result;
    }
}