package com.framework.activiti.model;

import java.io.Serializable;
import java.util.Arrays;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table wf_businodeperson
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 13 16:59:37 CST 2018
 */
public class WFBusiNodePerson extends BaseModel implements Serializable {
    /**
     * Database Column Remarks: nodepersonid
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.NODEPERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String nodepersonid;

    /**
     * Database Column Remarks: processdefid
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.PROCESSDEFID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String processdefid;

    /**
     * Database Column Remarks: 节点ID
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String nodeid;

    /**
     * Database Column Remarks: 人员或组别ID
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.PERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String personid;

    /**
     * Database Column Remarks: 指定当前配置的是人 员还是组别或角色
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.SETTYPE
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private Integer settype;

    /**
     * Database Column Remarks: 指定为某种业务设置的人员，当不设置时，即为空时，以节点配置为主，不为空时以业务配置为主
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.FORBUSINESS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String forbusiness;

    /**
     * Database Column Remarks: 指定为某个部门设置的人员，当不设置时，即为空时，以节点配置为主，不为空时以部门配置取节点的人员
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.DEPTID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String deptid;

    /**
     * Database Column Remarks: 1为启用，0未禁用
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private Integer status;

    /**
     * Database Column Remarks: remark
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_businodeperson.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private byte[] remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table wf_businodeperson
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.NODEPERSONID
     *
     * @return the value of wf_businodeperson.NODEPERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getNodepersonid() {
	return nodepersonid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.NODEPERSONID
     *
     * @param nodepersonid
     *            the value for wf_businodeperson.NODEPERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setNodepersonid(String nodepersonid) {
	this.nodepersonid = nodepersonid == null ? null : nodepersonid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.PROCESSDEFID
     *
     * @return the value of wf_businodeperson.PROCESSDEFID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getProcessdefid() {
	return processdefid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.PROCESSDEFID
     *
     * @param processdefid
     *            the value for wf_businodeperson.PROCESSDEFID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setProcessdefid(String processdefid) {
	this.processdefid = processdefid == null ? null : processdefid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.NODEID
     *
     * @return the value of wf_businodeperson.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getNodeid() {
	return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.NODEID
     *
     * @param nodeid
     *            the value for wf_businodeperson.NODEID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setNodeid(String nodeid) {
	this.nodeid = nodeid == null ? null : nodeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.PERSONID
     *
     * @return the value of wf_businodeperson.PERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getPersonid() {
	return personid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.PERSONID
     *
     * @param personid
     *            the value for wf_businodeperson.PERSONID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setPersonid(String personid) {
	this.personid = personid == null ? null : personid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.SETTYPE
     *
     * @return the value of wf_businodeperson.SETTYPE
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public Integer getSettype() {
	return settype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.SETTYPE
     *
     * @param settype
     *            the value for wf_businodeperson.SETTYPE
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setSettype(Integer settype) {
	this.settype = settype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.FORBUSINESS
     *
     * @return the value of wf_businodeperson.FORBUSINESS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getForbusiness() {
	return forbusiness;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.FORBUSINESS
     *
     * @param forbusiness
     *            the value for wf_businodeperson.FORBUSINESS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setForbusiness(String forbusiness) {
	this.forbusiness = forbusiness == null ? null : forbusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.DEPTID
     *
     * @return the value of wf_businodeperson.DEPTID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getDeptid() {
	return deptid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.DEPTID
     *
     * @param deptid
     *            the value for wf_businodeperson.DEPTID
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setDeptid(String deptid) {
	this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.STATUS
     *
     * @return the value of wf_businodeperson.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public Integer getStatus() {
	return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.STATUS
     *
     * @param status
     *            the value for wf_businodeperson.STATUS
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setStatus(Integer status) {
	this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_businodeperson.REMARK
     *
     * @return the value of wf_businodeperson.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public byte[] getRemark() {
	return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_businodeperson.REMARK
     *
     * @param remark
     *            the value for wf_businodeperson.REMARK
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setRemark(byte[] remark) {
	this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_businodeperson
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public Object getPrimaryKey() {
	return this.getNodepersonid();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_businodeperson
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public String toString() {
	StringBuilder sb = new StringBuilder();
	sb.append(getClass().getSimpleName());
	sb.append(" [");
	sb.append("Hash = ").append(hashCode());
	sb.append(", nodepersonid=").append(nodepersonid);
	sb.append(", processdefid=").append(processdefid);
	sb.append(", nodeid=").append(nodeid);
	sb.append(", personid=").append(personid);
	sb.append(", settype=").append(settype);
	sb.append(", forbusiness=").append(forbusiness);
	sb.append(", deptid=").append(deptid);
	sb.append(", status=").append(status);
	sb.append(", remark=").append(remark);
	sb.append(", serialVersionUID=").append(serialVersionUID);
	sb.append("]");
	return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_businodeperson
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public boolean equals(Object that) {
	if (this == that) {
	    return true;
	}
	if (that == null) {
	    return false;
	}
	if (getClass() != that.getClass()) {
	    return false;
	}
	WFBusiNodePerson other = (WFBusiNodePerson) that;
	return (this.getNodepersonid() == null ? other.getNodepersonid() == null
		: this.getNodepersonid().equals(other.getNodepersonid()))
		&& (this.getProcessdefid() == null ? other.getProcessdefid() == null
			: this.getProcessdefid().equals(other.getProcessdefid()))
		&& (this.getNodeid() == null ? other.getNodeid() == null : this.getNodeid().equals(other.getNodeid()))
		&& (this.getPersonid() == null ? other.getPersonid() == null
			: this.getPersonid().equals(other.getPersonid()))
		&& (this.getSettype() == null ? other.getSettype() == null
			: this.getSettype().equals(other.getSettype()))
		&& (this.getForbusiness() == null ? other.getForbusiness() == null
			: this.getForbusiness().equals(other.getForbusiness()))
		&& (this.getDeptid() == null ? other.getDeptid() == null : this.getDeptid().equals(other.getDeptid()))
		&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
		&& (Arrays.equals(this.getRemark(), other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_businodeperson
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((getNodepersonid() == null) ? 0 : getNodepersonid().hashCode());
	result = prime * result + ((getProcessdefid() == null) ? 0 : getProcessdefid().hashCode());
	result = prime * result + ((getNodeid() == null) ? 0 : getNodeid().hashCode());
	result = prime * result + ((getPersonid() == null) ? 0 : getPersonid().hashCode());
	result = prime * result + ((getSettype() == null) ? 0 : getSettype().hashCode());
	result = prime * result + ((getForbusiness() == null) ? 0 : getForbusiness().hashCode());
	result = prime * result + ((getDeptid() == null) ? 0 : getDeptid().hashCode());
	result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
	result = prime * result + (Arrays.hashCode(getRemark()));
	return result;
    }
}