package com.framework.activiti.model;

import java.io.Serializable;
import java.util.Arrays;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table wf_processinstanceform
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 13 16:59:36 CST 2018
 */
public class WfProcessInstanceForm extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processinstanceform.id
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processinstanceform.proinsid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String proinsid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processinstanceform.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private String applicationformid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processinstanceform.remark
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private byte[] remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table wf_processinstanceform
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processinstanceform.id
     *
     * @return the value of wf_processinstanceform.id
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getId() {
	return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processinstanceform.id
     *
     * @param id
     *            the value for wf_processinstanceform.id
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setId(String id) {
	this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processinstanceform.proinsid
     *
     * @return the value of wf_processinstanceform.proinsid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getProinsid() {
	return proinsid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processinstanceform.proinsid
     *
     * @param proinsid
     *            the value for wf_processinstanceform.proinsid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setProinsid(String proinsid) {
	this.proinsid = proinsid == null ? null : proinsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processinstanceform.applicationformid
     *
     * @return the value of wf_processinstanceform.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public String getApplicationformid() {
	return applicationformid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processinstanceform.applicationformid
     *
     * @param applicationformid
     *            the value for wf_processinstanceform.applicationformid
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setApplicationformid(String applicationformid) {
	this.applicationformid = applicationformid == null ? null : applicationformid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processinstanceform.remark
     *
     * @return the value of wf_processinstanceform.remark
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public byte[] getRemark() {
	return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processinstanceform.remark
     *
     * @param remark
     *            the value for wf_processinstanceform.remark
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    public void setRemark(byte[] remark) {
	this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processinstanceform
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public Object getPrimaryKey() {
	return this.getId();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processinstanceform
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public String toString() {
	StringBuilder sb = new StringBuilder();
	sb.append(getClass().getSimpleName());
	sb.append(" [");
	sb.append("Hash = ").append(hashCode());
	sb.append(", id=").append(id);
	sb.append(", proinsid=").append(proinsid);
	sb.append(", applicationformid=").append(applicationformid);
	sb.append(", remark=").append(remark);
	sb.append(", serialVersionUID=").append(serialVersionUID);
	sb.append("]");
	return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processinstanceform
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public boolean equals(Object that) {
	if (this == that) {
	    return true;
	}
	if (that == null) {
	    return false;
	}
	if (getClass() != that.getClass()) {
	    return false;
	}
	WfProcessInstanceForm other = (WfProcessInstanceForm) that;
	return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
		&& (this.getProinsid() == null ? other.getProinsid() == null
			: this.getProinsid().equals(other.getProinsid()))
		&& (this.getApplicationformid() == null ? other.getApplicationformid() == null
			: this.getApplicationformid().equals(other.getApplicationformid()))
		&& (Arrays.equals(this.getRemark(), other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processinstanceform
     *
     * @mbg.generated Sat Jan 13 16:59:37 CST 2018
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
	result = prime * result + ((getProinsid() == null) ? 0 : getProinsid().hashCode());
	result = prime * result + ((getApplicationformid() == null) ? 0 : getApplicationformid().hashCode());
	result = prime * result + (Arrays.hashCode(getRemark()));
	return result;
    }
}