package com.framework.activiti.model;

import java.io.Serializable;
import java.util.Arrays;

import com.framework.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table wf_processnodesetup
 *
 * @mbg.generated do_not_delete_during_merge Wed Jan 17 14:58:56 CST 2018
 */
public class WfProcessNodeSetup extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.process_Setup_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String processSetupId;

    /**
     * Database Column Remarks: 流程定义ID
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.process_Def_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String processDefId;

    /**
     * Database Column Remarks: 节点ID
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.node_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String nodeId;

    /**
     * Database Column Remarks: 节点名称
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.node_Name
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String nodeName;

    /**
     * Database Column Remarks: 节点是否启用，1为启用，0为禁用
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.status
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String status;

    /**
     * Database Column Remarks: 0、通用节点，1、与部门相关，2、与业务相关，3、与业务及部门相关
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.node_Type
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column wf_processnodesetup.remark
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private byte[] remark;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table wf_processnodesetup
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.process_Setup_Id
     *
     * @return the value of wf_processnodesetup.process_Setup_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getProcessSetupId() {
	return processSetupId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.process_Setup_Id
     *
     * @param processSetupId
     *            the value for wf_processnodesetup.process_Setup_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setProcessSetupId(String processSetupId) {
	this.processSetupId = processSetupId == null ? null : processSetupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.process_Def_Id
     *
     * @return the value of wf_processnodesetup.process_Def_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getProcessDefId() {
	return processDefId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.process_Def_Id
     *
     * @param processDefId
     *            the value for wf_processnodesetup.process_Def_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setProcessDefId(String processDefId) {
	this.processDefId = processDefId == null ? null : processDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.node_Id
     *
     * @return the value of wf_processnodesetup.node_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getNodeId() {
	return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.node_Id
     *
     * @param nodeId
     *            the value for wf_processnodesetup.node_Id
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setNodeId(String nodeId) {
	this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.node_Name
     *
     * @return the value of wf_processnodesetup.node_Name
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getNodeName() {
	return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.node_Name
     *
     * @param nodeName
     *            the value for wf_processnodesetup.node_Name
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setNodeName(String nodeName) {
	this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.status
     *
     * @return the value of wf_processnodesetup.status
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getStatus() {
	return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.status
     *
     * @param status
     *            the value for wf_processnodesetup.status
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setStatus(String status) {
	this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.node_Type
     *
     * @return the value of wf_processnodesetup.node_Type
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public String getNodeType() {
	return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.node_Type
     *
     * @param nodeType
     *            the value for wf_processnodesetup.node_Type
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setNodeType(String nodeType) {
	this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column wf_processnodesetup.remark
     *
     * @return the value of wf_processnodesetup.remark
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public byte[] getRemark() {
	return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column wf_processnodesetup.remark
     *
     * @param remark
     *            the value for wf_processnodesetup.remark
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    public void setRemark(byte[] remark) {
	this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processnodesetup
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    @Override
    public Object getPrimaryKey() {
	return this.getProcessSetupId();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processnodesetup
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    @Override
    public String toString() {
	StringBuilder sb = new StringBuilder();
	sb.append(getClass().getSimpleName());
	sb.append(" [");
	sb.append("Hash = ").append(hashCode());
	sb.append(", processSetupId=").append(processSetupId);
	sb.append(", processDefId=").append(processDefId);
	sb.append(", nodeId=").append(nodeId);
	sb.append(", nodeName=").append(nodeName);
	sb.append(", status=").append(status);
	sb.append(", nodeType=").append(nodeType);
	sb.append(", remark=").append(remark);
	sb.append(", serialVersionUID=").append(serialVersionUID);
	sb.append("]");
	return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processnodesetup
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
	if (this == that) {
	    return true;
	}
	if (that == null) {
	    return false;
	}
	if (getClass() != that.getClass()) {
	    return false;
	}
	WfProcessNodeSetup other = (WfProcessNodeSetup) that;
	return (this.getProcessSetupId() == null ? other.getProcessSetupId() == null
		: this.getProcessSetupId().equals(other.getProcessSetupId()))
		&& (this.getProcessDefId() == null ? other.getProcessDefId() == null
			: this.getProcessDefId().equals(other.getProcessDefId()))
		&& (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
		&& (this.getNodeName() == null ? other.getNodeName() == null
			: this.getNodeName().equals(other.getNodeName()))
		&& (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
		&& (this.getNodeType() == null ? other.getNodeType() == null
			: this.getNodeType().equals(other.getNodeType()))
		&& (Arrays.equals(this.getRemark(), other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table wf_processnodesetup
     *
     * @mbg.generated Wed Jan 17 14:58:56 CST 2018
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((getProcessSetupId() == null) ? 0 : getProcessSetupId().hashCode());
	result = prime * result + ((getProcessDefId() == null) ? 0 : getProcessDefId().hashCode());
	result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
	result = prime * result + ((getNodeName() == null) ? 0 : getNodeName().hashCode());
	result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
	result = prime * result + ((getNodeType() == null) ? 0 : getNodeType().hashCode());
	result = prime * result + (Arrays.hashCode(getRemark()));
	return result;
    }
}